"""
Nebula v9 — Intent Trigger Table, Data Lists, and Speak/Silent Sets
"""

_FACTS = ['Honey never expires — 3000-year-old honey found in Egypt was still edible.', 'A day on Venus is longer than a year on Venus.', 'The first computer bug was an actual bug — a moth found in 1947.', 'Octopuses have three hearts and blue blood.', "WiFi doesn't stand for 'Wireless Fidelity' — it's just a marketing name.", 'There are more stars in the universe than grains of sand on Earth.', "The world's first website went live on August 6, 1991.", "NASA's Apollo 11 computer had less processing power than a modern calculator.", 'The average person spends 6 months of their lifetime waiting at red lights.', "Linux powers 96.3% of the world's top 1 million web servers."]

_QUOTES = ['The only way to do great work is to love what you do. — Steve Jobs', 'In the middle of every difficulty lies opportunity. — Einstein', 'Innovation distinguishes a leader from a follower. — Steve Jobs', 'The secret of getting ahead is getting started. — Mark Twain', "Security is always excessive until it's not enough. — Roberta Grimes", 'Hack the planet. — Hackers, 1995', 'Move fast and break things. — Mark Zuckerberg', 'The best way to predict the future is to invent it. — Alan Kay', 'Simplicity is the ultimate sophistication. — Leonardo da Vinci', 'Any sufficiently advanced technology is indistinguishable from magic. — Arthur C. Clarke']

_AFFIRMATIONS = ['You are capable of amazing things. Every expert was once a beginner.', 'Your skills are valuable. Keep building, keep learning.', 'Today is full of potential. What will you create?', 'Every bug you fix makes you a better developer.', 'Progress, not perfection. Ship it.', "You've solved harder problems than this. You've got this.", 'Consistency beats intensity. Show up every day.', 'Your work matters. Keep going.']

_MAGIC8 = ['It is certain.', 'It is decidedly so.', 'Without a doubt.', 'Yes, definitely.', 'You may rely on it.', 'As I see it, yes.', 'Most likely.', 'Outlook good.', 'Yes.', 'Signs point to yes.', 'Reply hazy, try again.', 'Ask again later.', 'Better not tell you now.', 'Cannot predict now.', 'Concentrate and ask again.', "Don't count on it.", 'My reply is no.', 'My sources say no.', 'Outlook not so good.', 'Very doubtful.']

_SPEAK_EXECUTORS = {'cfg_agy_model_cheapest', 'cfg_agy_model_better', 'cfg_agy_model_best', 'cfg_agy_model_show', 'net_wifi_settings', 'p_sunrise', 'sci_element', 'tt_yaml_format', 'dev_hash', 'si2_locale', 'tt_word_freq', 'p2_days_between', 'tt_reverse_words', 'me_base_conv', 'si_battery', 'cfg_show_ai', 'p2_date_fmt', 'p_heart_rate', 'p2_days_left_year', 'p_alarm', 'tt_html_encode', 'me_pct_of', 'p_standup', 'cfg_set_mic', 'p2_moonphase', 'tt_acronym', 'p2_leap_year', 'cfg_show', 'cfg_show_search', 'ni_check', 'me_mortgage', 'fun_wyr', 'p_todo_show', 'p_worldclock', 'dev_git_diff', 'p_shopping', 'dev_git_status', 'p_bmi_q', 'p2_wordcount', 'tt_extract_urls', 'wn_weather', 'wn_news', 'net_routes', 'me_loan', 'p2_weeknum', 'p_week_num', 'tt_json_format', 'tt_kebab', 'fun_coin', 'cfg_toggle_maximize', 'si_swap', 'si_disk', 'mm_read_aloud', 'me_prime_factors', 'dev_py_format', 'fun_joke', 'si_hostname', 'tt_palindrome', 'p2_date_add', 'tt_title', 'p_boil_eggs', 'tt_spelling', 'cfg_toggle_tts', 'p2_add_days', 'tt_upper', 'p_clip_hist', 'me_tax', 'p_habit_show', 'p_month_days', 'dev_ver_py', 'dev_release_notes', 'si2_last_logins', 'net_revdns', 'p_days_until', 'me_simplify', 'si2_cron_list', 'se_hash_text', 'tt_url_encode', 'tt_ascii_table', 'p2_charcount', 'p2_stopwatch', 'net_dns_lookup', 'p_time_diff', 'cfg_show_browser', 'sys_battery', 'tt_synonym', 'fun_word_day', 'si2_netstat', 'fun_rand_word', 'fun_magic8', 'p_journal_read', 'p_unit_conv', 'dev_color_hex', 'p_calendar', 'tt_json_validate', 'me_matrix', 'si2_audio', 'se_failed_logins', 'net_firewall', 'fun_teaser', 'p2_week_num', 'dev_git_log', 'cfg_set_energy', 'me_compound', 'p_split_bill', 'p_med_reminder', 'fun_trivia', 'tt_rhyme', 'p2_tz_convert', 'net_vpn_status', 'tt_reverse', 'tt_extract_emails', 'cfg_toggle_yolo', 'sys_info', 'p_age_calc', 'dev_b64dec', 'p_date_add', 'me_unit_conv', 'p_time', 'dev_localhost', 'net_bluetooth', 'me_stats', 'p2_what_day', 'me_cup_convert', 'si_uptime', 'fun_word_game', 'cfg_show_stt', 'dev_docker_help', 'dev_b64enc', 'wn_exchange', 'sys_hostname', 'net_ping_test', 'net_whois', 'me_discount', 'p_define', 'wn_stock', 'p2_month_days', 'p_countdown', 'dev_cron', 'si2_mounted', 'si2_autostart', 'dev_commit_msg', 'cfg_list_mics', 'p2_qr_code', 'cfg_set_dynamic', 'p_notes_read', 'nova_ask', 'p_password', 'p_quarter', 'dev_regex_cheat', 'mm_list_bookmarks', 'si2_screen_time', 'p_steps', 'p2_sunrise', 'me_interest', 'p_leap_year', 'tt_count_vowels', 'p2_age_calc', 'p2_percentage', 'fun_affirm', 'tt_antonym', 'p_reminders_show', 'dev_ver_node', 'si2_tz', 'p2_epoch', 'p_reminders_clear', 'si_cpu', 'nova_status', 'me_fibonacci', 'p2_clip_copy', 'p_kanban', 'me_bmi', 'p_cook_timer', 'p_flight_est', 'p2_next_weekday', 'p_calc', 'dev_uuid', 'p_distance', 'fun_recipe', 'p2_flight_est', 'dev_json_format', 'si_info', 'dev_pytest', 'p_biz_days', 'net_headers', 'tt_sentence', 'tt_url_decode', 'p_date', 'p_sms_draft', 'sys_uptime', 'si2_summary', 'dev_make', 'si2_open_files', 'tt_shortcuts', 'p_linkedin', 'tt_sort_lines', 'net_mac', 'me_solve', 'p2_lorem', 'fun_8ball', 'p_reading_list', 'me_is_prime', 'me_sdt', 'p_add_days', 'dev_py_lint', 'p2_reading_time', 'fun_word', 'fun_dice', 'p_habit', 'p_day', 'b2_translate_text', 'me_derivative', 'tt_lower', 'ni_interfaces', 'tt_camel', 'si2_resolution', 'p_exercise', 'si2_syslog', 'si2_osver', 'p_date_fmt', 'si2_public_ip', 'p_world_time', 'p_clip_copy', 'me_tip', 'fun_fact', 'dev_ver_npm', 'dev_open_ports', 'mm_read_clipboard', 'p_bp', 'tt_pascal', 'net_ping', 'dev_gitignore', 'si2_lsusb', 'net_devices', 'si2_lspci', 'dev_git_branch', 'me_gcd', 'p2_clip_pwd', 'fun_quote', 'p_email_draft', 'si2_gpu', 'p_moonphase', 'p_days_left_year', 'dev_sql_help', 'wn_moon_phase', 'dev_port_check', 'p_rng', 'si2_fonts', 'p_next_weekday', 'ni_wifi', 'p2_quarter', 'tt_unique_lines', 'me_integral', 'tt_grammar', 'si2_svc_list', 'si_ram', 'p_focus', 'me_quadratic', 'fun_greet', 'ni_ip', 'p_days_between', 'fun_rand_choice', 'net_speed', 'dev_ver_git', 'si2_kernel', 'wn_crypto', 'fun_rand_num', 'p_sleep', 'fun_riddle', 'si_temp', 'net_ssl_check', 'tt_rot13', 'tt_html_decode', 'si2_whoami', 'wn_ipinfo', 'net_traceroute', 'mm_list_software', 'p2_distance', 'net_wifi_pass', 'tt_extract_numbers', 'si2_lsblk', 'me_data_size', 'se_pw_strength', 'fun_shuffle', 'dev_git_help', 'net_scan_local', 'p2_clip_read', 'sec_show_ssh', 'tt_snake', 'p_clipboard', 'si2_iostat', 'dev_http_status', 'p2_biz_days', 'dev_env_vars', 'p2_world_time', 'tt_slugify', 'cfg_test_mic', 'p2_time_diff', 'tt_char_freq', 'dev_char_code', 'me_savings', 'me_factorial', 'p_percentage', 'p_what_day', 'sci_constant', 'si2_font_size', 'mm_read_selection', 'dev_markdown', 'p2_worldclock', 'si_proc_list'}

_SILENT_EXECUTORS = {'mm_arrow_right', 'fs_symlink', 'web_reddit', 'dev_docker_rm', 'app_edge', 'a2_notion', 'p_remind', 'dev_git_stash', 'mm_type_text', 'mm_img_resize', 'a2_slack', 'sys_airplane_on', 'web_open_regex101', 'dev_docker_build', 'sys_close_window', 'web_open_calendar', 'p_alarm', 'win_always_top', 'cfg_set_mic', 'a2_photos', 'app_excel', 'web_open_spotify', 'fs_unzip', 'dev_npm_start', 'nova_install_gemini', 'mm_page_dn', 'sys_clear_temp', 'sys_unmute', 'p_note_add', 'web_chatgpt', 'cl_find_old', 'mm_open_bookmark', 'web_open_gmail', 'a2_android_studio', 'w2_fullscreen', 'nova_off', 'b2_mdn', 'mm_yt_audio', 'fs_cp_file', 'p_habit_add', 'sys_bell', 'dev_git_push', 'a2_music', 'se_passphrase', 'win_snap_left', 'p_type', 'a2_colab', 'mm_volume_up', 'web_ask_perplexity', 'dev_open_proj', 'b2_regex', 'b2_stackoverflow', 'clip_paste', 'sys_hotspot_on', 'web_claude', 'cfg_set_theme', 'sys_bt_off', 'web_bing', 'mm_escape', 'app_explorer', 'mm_reopen_tab', 'dev_git_commit', 'mm_minimize_app', 'web_open_instagram', 'dev_git_remote', 'm2_record_audio', 'mm_emoji', 'fs_cp_dir', 'web_open_youtube', 'web_open_whatsapp', 'web_gemini', 'fs_del_empty', 'cl_find_large', 'mm_enter', 'dev_git_init', 'app_open', 'web_open_notion', 'a2_nvim', 'fs_shortcut', 'b2_notion', 'cl_tree', 'mm_redo', 'web_github', 'b2_trello', 'cfg_set_api_key', 'fs_touch', 'sys_ss', 'mm_home_key', 'dev_docker_pull', 'dev_docker_images', 'web_maps', 'web_images', 'a2_postman', 'win_max', 'p_todo_clear', 'dev_git_tag', 'sys_shutdown', 'sys_restart', 'sys_snipping', 'web_perplexity', 'dev_git_stash_pop', 'app_notepad', 'mm_tab_prev', 'cfg_set_energy', 'app_paint', 'sys_taskmgr', 'bc_history', 'web_yt_search', 'win_snap_right', 'mm_arrow_left', 'a2_jira', 'bc_bookmark', 'bc_refresh', 'mm_research', 'fs_rename', 'web_open_site_smart', 'cfg_set_ai', 'dev_npm_install', 'mm_img_convert', 'dev_git_pull', 'mm_play_pause', 'sys_br_set', 'a2_zoom', 'sys_vol_max', 'se_encrypt', 'sys_logout', 'cfg_set_stt', 'mm_prev', 'web_open_trello', 'web_open_gemini', 'app_vlc', 'web_gmail', 'sys_br_up', 'mm_task_view', 'a2_audacity', 'dev_git_add', 'mm_cut', 'mm_magnifier', 'p_pomodoro', 'web_open_facebook', 'cfg_set_dynamic', 'fs_open_loc', 'web_ddg', 'sys_refresh', 'p_notes_clear', 'web_facebook', 'sys_dark_mode', 'mm_copy', 'mm_delete_key', 'p_timer', 'edit_select_all', 'app_spotify', 'fs_org_dl', 'sys_mute', 'web_open_reddit', 'mm_maximize_app', 'b2_webcheck', 'sys_notify', 'a2_teams', 'web_twitter', 'bc_downloads', 'web_open_drive', 'sys_notif_center', 'cfg_set_browser', 'mm_backspace', 'web_wiki', 'dev_git_checkout', 'dev_npm_build', 'mm_incognito_here', 'web_open_mdn', 'dev_apt_remove', 'web_amazon_search', 'sys_empty_bin', 'mm_add_bookmark', 'mm_scroll_down', 'web_search_incognito', 'fs_del_dir', 'sys_wifi_off', 'a2_gimp', 'bc_new_tab', 'bc_back', 'b2_twitter', 'sys_lock', 'sys_vol_up', 'mm_next', 'fs_del_file', 'w2_snap_left', 'mm_lock', 'web_ask_claude', 'web_open_npmjs', 'mm_end_key', 'web_open_site', 'web_url', 'dev_pip_update', 'web_open_producthunt', 'sys_wallpaper', 'sys_cancel_shutdown', 'dev_docker_ps', 'p_journal', 'dev_venv', 'mm_undo', 'fs_mv_dir', 'fs_zip', 'mm_tab_key', 'se_decrypt', 'web_translate', 'bc_page_up', 'web_open_private', 'a2_replit', 'app_close_all', 'mm_scroll_up', 'web_quick_link', 'app_word', 'web_open_stackoverflow', 'win_switch', 'sec_ssh_keygen', 'a2_whatsapp', 'dev_pip_list', 'm2_play_file', 'mm_tab_n', 'nova_on', 'app_close', 'mm_webcam_photo', 'mm_snip', 'p_todo_add', 'a2_discord', 'bc_forward', 'web_scholar', 'app_open_smart', 'sys_empty_trash', 'web_open_claude', 'cl_find_duplicates', 'mm_find_text', 'b2_devdocs', 'web_open_netflix', 'b2_pypi', 'w2_snap_right', 'mm_close_window', 'web_twitch', 'clip_copy_sel', 'a2_figma', 'sys_sleep', 'fs_append', 'b2_response_time', 'b2_translate', 'mm_screenshot', 'sys_bt_on', 'mm_volume_down', 'web_open_twitter', 'bc_reopen_tab', 'dev_docker_stop', 'app_terminal', 'mm_arrow_dn', 'fs_mv_file', 'dev_pip_freeze', 'a2_open', 'mm_arrow_up', 'dev_docker_logs', 'a2_dbeaver', 'cl_clean', 'dev_run_py', 'cl_free_mem', 'mm_paste', 'web_ask_gemini', 'app_firefox', 'mm_tab_next', 'web_open_pypi', 'dev_pip_install', 'dev_port_check', 'nova_auth', 'cfg_set_search', 'cl_find_empty', 'sys_vol_min', 'web_netflix', 'app_powerpoint', 'dev_apt_install', 'dev_http_serve', 'a2_obs', 'mm_restore_app', 'sec_shred', 'web_open_chatgpt', 'app_brave', 'mm_play_file', 'web_instagram', 'mm_search_incognito', 'clip_cut', 'sys_magnifier', 'edit_undo', 'dev_git_merge', 'mm_go_forward', 'web_open_github', 'w2_always_top', 'dev_docker_start', 'win_min_all', 'fs_backup', 'cl_find_hidden', 'm2_record_screen', 'web_google', 'mm_yt_video', 'sys_wifi_on', 'mm_scroll_dn', 'mm_space_key', 'cl_apt_clean', 'a2_telegram', 'web_open_perplexity', 'sys_br_dn', 'sys_vol_dn', 'dev_git_clone', 'app_chrome', 'app_vscode', 'web_youtube', 'dev_npm_run', 'mm_switch_window', 'edit_redo', 'dev_npm_list', 'nova_clear', 'sys_clip_clear', 'web_ask_chatgpt', 'mm_open_software', 'fs_open', 'bc_page_down', 'web_research', 'sys_night_mode', 'app_calc', 'fs_mkdir', 'app_settings', 'sys_task_view', 'fs_make_exec', 'dev_run_sh', 'dev_npm_test', 'dev_npm_outdated', 'dev_apt_update', 'cfg_test_mic', 'mm_notification_center', 'web_open_hackernews', 'dev_git_reset', 'a2_canva', 'web_linkedin', 'mm_show_desktop', 'mm_go_back', 'web_open_linkedin', 'b2_linkedin', 'bc_close_tab', 'web_open_url', 'mm_select_all', 'web_open_twitch', 'vt_type', 'mm_page_up', 'sys_vol_set'}

_CMD_TABLE = [
    ({'time'}, ('p_time', 1.0)),
    ({'what', 'time'}, ('p_time', 1.0)),
    ({'clock'}, ('p_time', 0.9)),
    ({'date'}, ('p_date', 1.0)),
    ({'today'}, ('p_date', 0.9)),
    ({'day'}, ('p_day', 0.9)),
    ({'week', 'number'}, ('p2_weeknum', 1.0)),
    ({'current', 'week'}, ('p2_weeknum', 0.9)),
    ({'epoch'}, ('p2_epoch', 1.5)),
    ({'epoch', 'time'}, ('p2_epoch', 2.0)),
    ({'unix', 'timestamp'}, ('p2_epoch', 1.0)),
    ({'days', 'until'}, ('p_days_until', 1.0)),
    ({'world', 'clock'}, ('p2_worldclock', 1.0)),
    ({'timezone'}, ('p2_worldclock', 0.9)),
    ({'calendar'}, ('p_calendar', 1.0)),
    ({'up', 'volume'}, ('sys_vol_up', 1.0)),
    ({'louder'}, ('sys_vol_up', 0.9)),
    ({'increase', 'volume'}, ('sys_vol_up', 1.0)),
    ({'volume', 'down'}, ('sys_vol_dn', 1.0)),
    ({'quieter'}, ('sys_vol_dn', 0.9)),
    ({'decrease', 'volume'}, ('sys_vol_dn', 1.0)),
    ({'mute'}, ('sys_mute', 1.0)),
    ({'silence'}, ('sys_mute', 0.8)),
    ({'unmute'}, ('sys_unmute', 1.0)),
    ({'max', 'volume'}, ('sys_vol_max', 1.0)),
    ({'set', 'volume'}, ('sys_vol_set', 1.0)),
    ({'set', 'volume'}, ('sys_vol_set', 1.0)),
    ({'volume'}, ('sys_vol_set', 0.6)),
    ({'vol'}, ('sys_vol_set', 0.6)),
    ({'adjust', 'volume'}, ('sys_vol_set', 1.0)),
    ({'change', 'volume'}, ('sys_vol_set', 1.0)),
    ({'to', 'volume'}, ('sys_vol_set', 1.0)),
    ({'screenshot'}, ('sys_ss', 1.0)),
    ({'screen', 'capture'}, ('sys_ss', 1.0)),
    ({'screen', 'capture'}, ('sys_ss', 1.0)),
    ({'brightness', 'up'}, ('sys_br_up', 1.0)),
    ({'brightness', 'increase'}, ('sys_br_up', 1.0)),
    ({'brightness', 'down'}, ('sys_br_dn', 1.0)),
    ({'brightness', 'decrease'}, ('sys_br_dn', 1.0)),
    ({'reduce', 'brightness'}, ('sys_br_dn', 1.0)),
    ({'brightness', 'lower'}, ('sys_br_dn', 1.0)),
    ({'dim', 'brightness'}, ('sys_br_dn', 1.0)),
    ({'screen', 'dim'}, ('sys_br_dn', 1.0)),
    ({'raise', 'brightness'}, ('sys_br_up', 1.0)),
    ({'screen', 'brighten'}, ('sys_br_up', 1.0)),
    ({'brightness', 'set'}, ('sys_br_set', 1.0)),
    ({'brightness', 'set'}, ('sys_br_set', 1.0)),
    ({'brightness', 'to'}, ('sys_br_set', 0.9)),
    ({'mode', 'night'}, ('sys_night', 1.0)),
    ({'light', 'night'}, ('sys_night', 1.0)),
    ({'blue', 'light'}, ('sys_night', 1.0)),
    ({'shutdown'}, ('sys_shutdown', 1.0)),
    ({'shut', 'down'}, ('sys_shutdown', 1.0)),
    ({'off', 'power'}, ('sys_shutdown', 1.0)),
    ({'restart'}, ('sys_restart', 1.0)),
    ({'reboot'}, ('sys_restart', 1.0)),
    ({'sleep'}, ('sys_sleep', 1.0)),
    ({'hibernate'}, ('sys_sleep', 1.0)),
    ({'suspend'}, ('sys_sleep', 1.0)),
    ({'shutdown', 'cancel'}, ('sys_cancel_sd', 1.0)),
    ({'logout'}, ('sys_logout', 1.0)),
    ({'log', 'out'}, ('sys_logout', 1.0)),
    ({'out', 'sign'}, ('sys_logout', 1.0)),
    ({'lock'}, ('sys_lock', 1.0)),
    ({'screen', 'lock'}, ('sys_lock', 1.0)),
    ({'empty', 'bin'}, ('sys_empty_bin', 1.0)),
    ({'empty', 'trash'}, ('sys_empty_bin', 1.0)),
    ({'clear', 'temp'}, ('sys_clear_temp', 1.0)),
    ({'clean', 'temp'}, ('sys_clear_temp', 1.0)),
    ({'cache', 'clear'}, ('sys_clear_temp', 0.9)),
    ({'task', 'manager'}, ('sys_taskmgr', 1.0)),
    ({'activity', 'monitor'}, ('sys_taskmgr', 1.0)),
    ({'refresh'}, ('sys_refresh', 1.0)),
    ({'wallpaper'}, ('sys_wallpaper', 1.0)),
    ({'background'}, ('sys_wallpaper', 0.8)),
    ({'notify'}, ('sys_notify', 0.9)),
    ({'notification'}, ('sys_notify', 0.9)),
    ({'bell'}, ('sys_bell', 1.0)),
    ({'beep'}, ('sys_bell', 1.0)),
    ({'hostname'}, ('sys_hostname', 1.0)),
    ({'computer', 'name'}, ('sys_hostname', 1.0)),
    ({'clipboard', 'clear'}, ('clip_clear', 1.0)),
    ({'clipboard', 'clear'}, ('clip_clear', 1.0)),
    ({'type'}, ('vt_type', 1.0)),
    ({'type', 'auto'}, ('vt_type', 1.0)),
    ({'cpu'}, ('si_cpu', 1.0)),
    ({'processor'}, ('si_cpu', 0.9)),
    ({'ram'}, ('si_ram', 1.0)),
    ({'memory'}, ('si_ram', 0.9)),
    ({'disk'}, ('si_disk', 1.0)),
    ({'space', 'disk'}, ('si_disk', 1.0)),
    ({'battery'}, ('si_battery', 1.0)),
    ({'system', 'info'}, ('si_info', 1.0)),
    ({'sysinfo'}, ('si_info', 1.0)),
    ({'uptime'}, ('si_uptime', 1.0)),
    ({'system', 'monitor'}, ('si_monitor', 1.0)),
    ({'processes'}, ('si_proc_list', 1.0)),
    ({'processes', 'running'}, ('si_proc_list', 1.0)),
    ({'zombie'}, ('si_zombies', 1.0)),
    ({'gpu'}, ('si2_gpu', 1.0)),
    ({'card', 'graphics'}, ('si2_gpu', 1.0)),
    ({'temp', 'cpu'}, ('si2_temp', 1.0)),
    ({'swap'}, ('si2_swap', 1.0)),
    ({'whoami'}, ('si2_whoami', 1.0)),
    ({'public', 'ip'}, ('ni_ip', 1.0)),
    ({'syslog'}, ('si2_syslog', 1.0)),
    ({'kernel'}, ('si2_kernel', 1.0)),
    ({'os', 'version'}, ('si2_osver', 1.0)),
    ({'last', 'logins'}, ('si2_last_logins', 1.0)),
    ({'services'}, ('si2_svc_list', 0.9)),
    ({'services', 'running'}, ('si2_svc_list', 1.0)),
    ({'mounted'}, ('si2_mounted', 1.0)),
    ({'usb'}, ('si2_lsusb', 1.0)),
    ({'devices', 'usb'}, ('si2_lsusb', 1.0)),
    ({'devices', 'block'}, ('si2_lsblk', 1.0)),
    ({'netstat'}, ('si2_netstat', 1.0)),
    ({'address', 'ip'}, ('ni_ip', 1.0)),
    ({'ip', 'my'}, ('ni_ip', 1.0)),
    ({'local', 'ip'}, ('ni_ip', 1.0)),
    ({'internet', 'check'}, ('ni_check', 1.0)),
    ({'internet', 'connection'}, ('ni_check', 1.0)),
    ({'online'}, ('ni_check', 0.8)),
    ({'online', 'am'}, ('ni_check', 1.0)),
    ({'wifi'}, ('ni_wifi', 1.0)),
    ({'wifi', 'name'}, ('ni_wifi', 1.0)),
    ({'network', 'interfaces'}, ('ni_interfaces', 1.0)),
    ({'ping'}, ('net_ping', 1.0)),
    ({'dns', 'flush'}, ('net_flushdns', 1.0)),
    ({'dns', 'clear'}, ('net_flushdns', 1.0)),
    ({'traceroute'}, ('net_traceroute', 1.0)),
    ({'whois'}, ('net_whois', 1.0)),
    ({'dns', 'reverse'}, ('net_revdns', 1.0)),
    ({'headers'}, ('net_headers', 1.0)),
    ({'http', 'headers'}, ('net_headers', 1.0)),
    ({'test', 'speed'}, ('net_speed', 1.0)),
    ({'internet', 'speed'}, ('net_speed', 1.0)),
    ({'ssl', 'check'}, ('net_ssl_check', 1.0)),
    ({'certificate', 'ssl'}, ('net_ssl_check', 1.0)),
    ({'network', 'scan'}, ('net_scan_local', 1.0)),
    ({'local', 'devices'}, ('net_scan_local', 1.0)),
    ({'dns', 'lookup'}, ('net_dns_lookup', 1.0)),
    ({'nslookup'}, ('net_dns_lookup', 1.0)),
    ({'download', 'file'}, ('net_download', 1.0)),
    ({'settings', 'wifi'}, ('net_wifi_settings', 1.0)),
    ({'bluetooth'}, ('net_bluetooth', 1.0)),
    ({'firewall'}, ('net_firewall', 1.0)),
    ({'ports', 'open'}, ('dev_open_ports', 1.0)),
    ({'ports', 'listening'}, ('dev_open_ports', 1.0)),
    ({'chrome', 'open'}, ('app_chrome', 1.0)),
    ({'chrome', 'launch'}, ('app_chrome', 1.0)),
    ({'chrome'}, ('app_chrome', 0.9)),
    ({'firefox', 'open'}, ('app_firefox', 1.0)),
    ({'firefox'}, ('app_firefox', 0.9)),
    ({'edge', 'open'}, ('app_edge', 1.0)),
    ({'edge', 'microsoft'}, ('app_edge', 1.0)),
    ({'brave', 'open'}, ('app_brave', 1.0)),
    ({'brave', 'browser'}, ('app_brave', 1.0)),
    ({'terminal'}, ('app_terminal', 1.0)),
    ({'terminal', 'open'}, ('app_terminal', 1.0)),
    ({'prompt', 'command'}, ('app_terminal', 1.0)),
    ({'calculator'}, ('app_calc', 1.0)),
    ({'calculator', 'open'}, ('app_calc', 1.0)),
    ({'notepad'}, ('app_notepad', 1.0)),
    ({'editor', 'text'}, ('app_notepad', 0.9)),
    ({'manager', 'file'}, ('app_explorer', 1.0)),
    ({'file', 'explorer'}, ('app_explorer', 1.0)),
    ({'settings', 'system'}, ('app_settings', 1.0)),
    ({'preferences'}, ('app_settings', 0.9)),
    ({'vscode', 'open'}, ('app_vscode', 1.0)),
    ({'vscode'}, ('app_vscode', 0.9)),
    ({'visual', 'studio', 'code'}, ('app_vscode', 1.0)),
    ({'spotify', 'open'}, ('app_spotify', 1.0)),
    ({'spotify'}, ('app_spotify', 0.9)),
    ({'vlc', 'open'}, ('app_vlc', 1.0)),
    ({'vlc'}, ('app_vlc', 0.9)),
    ({'paint'}, ('app_paint', 0.9)),
    ({'word', 'open'}, ('app_word', 1.0)),
    ({'microsoft', 'word'}, ('app_word', 1.0)),
    ({'excel', 'open'}, ('app_excel', 1.0)),
    ({'microsoft', 'excel'}, ('app_excel', 1.0)),
    ({'discord', 'open'}, ('a2_discord', 1.0)),
    ({'discord'}, ('a2_discord', 0.9)),
    ({'slack', 'open'}, ('a2_slack', 1.0)),
    ({'slack'}, ('a2_slack', 0.9)),
    ({'telegram', 'open'}, ('a2_telegram', 1.0)),
    ({'telegram'}, ('a2_telegram', 0.9)),
    ({'zoom', 'open'}, ('a2_zoom', 1.0)),
    ({'zoom'}, ('a2_zoom', 0.9)),
    ({'whatsapp'}, ('a2_whatsapp', 1.0)),
    ({'gimp', 'open'}, ('a2_gimp', 1.0)),
    ({'gimp'}, ('a2_gimp', 0.9)),
    ({'obs', 'open'}, ('a2_obs', 1.0)),
    ({'obs'}, ('a2_obs', 0.9)),
    ({'audacity', 'open'}, ('a2_audacity', 1.0)),
    ({'audacity'}, ('a2_audacity', 0.9)),
    ({'figma'}, ('a2_figma', 0.9)),
    ({'canva'}, ('a2_canva', 0.9)),
    ({'postman'}, ('a2_postman', 0.9)),
    ({'neovim'}, ('a2_nvim', 1.0)),
    ({'nvim'}, ('a2_nvim', 1.0)),
    ({'replit'}, ('a2_replit', 0.9)),
    ({'colab'}, ('a2_colab', 0.9)),
    ({'close', 'app'}, ('app_close', 1.0)),
    ({'app', 'quit'}, ('app_close', 1.0)),
    ({'minimize', 'all'}, ('win_min_all', 1.0)),
    ({'show', 'desktop'}, ('win_min_all', 1.0)),
    ({'maximize'}, ('win_max', 1.0)),
    ({'snap', 'left'}, ('w2_snap_left', 1.0)),
    ({'snap', 'right'}, ('w2_snap_right', 1.0)),
    ({'fullscreen'}, ('w2_fullscreen', 1.0)),
    ({'top', 'always'}, ('w2_always_top', 1.0)),
    ({'search'}, ('web_search', 1.0)),
    ({'google'}, ('web_google', 0.9)),
    ({'bing'}, ('web_bing', 0.9)),
    ({'duckduckgo'}, ('web_ddg', 1.0)),
    ({'search', 'image'}, ('web_images', 1.0)),
    ({'images', 'search'}, ('web_images', 1.0)),
    ({'google', 'images'}, ('web_images', 1.0)),
    ({'maps'}, ('web_maps', 0.9)),
    ({'google', 'maps'}, ('web_maps', 1.0)),
    ({'wikipedia'}, ('web_wiki', 1.0)),
    ({'wiki'}, ('web_wiki', 0.8)),
    ({'youtube', 'search'}, ('web_yt_search', 1.3)),
    ({'search', 'claude'}, ('web_ask_claude', 1.3)),
    ({'search', 'gemini'}, ('web_ask_gemini', 1.3)),
    ({'search', 'chatgpt'}, ('web_ask_chatgpt', 1.3)),
    ({'search', 'perplexity'}, ('web_ask_perplexity', 1.3)),
    ({'reddit', 'search'}, ('web_reddit_search', 1.3)),
    ({'search', 'github'}, ('web_github_search', 1.3)),
    ({'search', 'amazon'}, ('web_amazon_search', 1.3)),
    ({'web', 'messages'}, ('web_messages', 1.3)),
    ({'google', 'messages'}, ('web_messages', 1.3)),
    ({'messages', 'open'}, ('web_messages', 1.2)),
    ({'scholar'}, ('web_scholar', 0.9)),
    ({'google', 'scholar'}, ('web_scholar', 1.0)),
    ({'chatgpt', 'ask'}, ('web_ask_chatgpt', 1.0)),
    ({'claude', 'ask'}, ('web_ask_claude', 1.0)),
    ({'ask', 'gemini'}, ('web_ask_gemini', 1.0)),
    ({'perplexity', 'ask'}, ('web_ask_perplexity', 1.0)),
    ({'ai', 'ask'}, ('web_ask_default_ai', 1.0)),
    ({'url', 'open'}, ('web_url', 1.0)),
    ({'youtube', 'open'}, ('web_youtube', 1.0)),
    ({'youtube'}, ('web_youtube', 0.9)),
    ({'gmail', 'open'}, ('web_gmail', 1.0)),
    ({'gmail'}, ('web_gmail', 0.9)),
    ({'github', 'open'}, ('web_github', 1.0)),
    ({'github'}, ('web_github', 0.9)),
    ({'reddit', 'open'}, ('web_reddit', 1.0)),
    ({'reddit'}, ('web_reddit', 0.9)),
    ({'netflix', 'open'}, ('web_netflix', 1.0)),
    ({'netflix'}, ('web_netflix', 0.9)),
    ({'chatgpt', 'open'}, ('web_chatgpt', 1.0)),
    ({'chatgpt'}, ('web_chatgpt', 0.9)),
    ({'claude', 'open'}, ('web_claude', 1.0)),
    ({'twitter'}, ('b2_twitter', 0.9)),
    ({'x.com'}, ('b2_twitter', 1.0)),
    ({'linkedin'}, ('b2_linkedin', 0.9)),
    ({'stackoverflow'}, ('b2_stackoverflow', 1.0)),
    ({'overflow', 'stack'}, ('b2_stackoverflow', 1.0)),
    ({'notion'}, ('b2_notion', 0.9)),
    ({'trello'}, ('b2_trello', 0.9)),
    ({'pypi'}, ('b2_pypi', 1.0)),
    ({'mdn'}, ('b2_mdn', 1.0)),
    ({'devdocs'}, ('b2_devdocs', 1.0)),
    ({'regex101'}, ('b2_regex', 1.0)),
    ({'translate'}, ('b2_translate', 0.9)),
    ({'google', 'translate'}, ('b2_translate', 1.0)),
    ({'browser', 'private'}, ('web_private', 1.0)),
    ({'incognito'}, ('web_private', 1.0)),
    ({'window', 'private'}, ('web_private', 1.0)),
    ({'tab', 'private'}, ('web_private', 1.0)),
    ({'close', 'tab'}, ('bc_close_tab', 1.0)),
    ({'close', 'this', 'tab'}, ('bc_close_tab', 1.1)),
    ({'tab', 'new'}, ('bc_new_tab', 1.0)),
    ({'tab', 'new', 'open'}, ('bc_new_tab', 1.1)),
    ({'switch', 'tab'}, ('bc_new_tab', 0.8)),
    ({'next', 'tab'}, ('bc_new_tab', 0.9)),
    ({'refresh', 'tab'}, ('bc_refresh', 1.1)),
    ({'reload', 'tab'}, ('bc_refresh', 1.1)),
    ({'page', 'refresh'}, ('bc_refresh', 1.1)),
    ({'reload', 'page'}, ('bc_refresh', 1.1)),
    ({'back', 'go'}, ('bc_back', 1.0)),
    ({'back', 'browser'}, ('bc_back', 1.0)),
    ({'go', 'forward'}, ('bc_forward', 1.0)),
    ({'browser', 'forward'}, ('bc_forward', 1.0)),
    ({'next', 'page'}, ('bc_forward', 0.8)),
    ({'page', 'previous'}, ('bc_back', 0.8)),
    ({'show', 'history'}, ('bc_history', 1.0)),
    ({'browser', 'history'}, ('bc_history', 1.0)),
    ({'downloads', 'show'}, ('bc_downloads', 1.0)),
    ({'browser', 'downloads'}, ('bc_downloads', 1.0)),
    ({'page', 'bookmark'}, ('bc_bookmark', 1.0)),
    ({'save', 'bookmark'}, ('bc_bookmark', 1.0)),
    ({'tab', 'reopen'}, ('bc_reopen_tab', 1.0)),
    ({'page', 'reopen'}, ('bc_reopen_tab', 1.0)),
    ({'page', 'up'}, ('bc_page_up', 1.0)),
    ({'page', 'down'}, ('bc_page_down', 1.0)),
    ({'find', 'text'}, ('mm_find_text', 1.0)),
    ({'on', 'page', 'find'}, ('mm_find_text', 1.0)),
    ({'copy'}, ('clip_copy_sel', 1.0)),
    ({'selection', 'copy'}, ('clip_copy_sel', 1.1)),
    ({'paste'}, ('clip_paste', 1.0)),
    ({'cut'}, ('clip_cut', 1.0)),
    ({'all', 'select'}, ('edit_select_all', 1.0)),
    ({'undo'}, ('edit_undo', 1.0)),
    ({'redo'}, ('edit_redo', 1.0)),
    ({'center', 'notification'}, ('sys_notif_center', 1.0)),
    ({'center', 'action'}, ('sys_notif_center', 1.0)),
    ({'magnifier'}, ('sys_magnifier', 1.0)),
    ({'magnify'}, ('sys_magnifier', 0.9)),
    ({'snip'}, ('sys_snipping', 1.0)),
    ({'snipping', 'tool'}, ('sys_snipping', 1.0)),
    ({'screenshot', 'tool'}, ('sys_snipping', 1.0)),
    ({'view', 'task'}, ('sys_task_view', 1.0)),
    ({'all', 'windows'}, ('sys_task_view', 1.0)),
    ({'close', 'window'}, ('sys_close_window', 1.0)),
    ({'close', 'this', 'window'}, ('sys_close_window', 1.1)),
    ({'research'}, ('web_research', 1.0)),
    ({'on', 'research'}, ('web_research', 0.9)),
    ({'search', 'incognito'}, ('web_search_incognito', 1.2)),
    ({'search', 'incognito'}, ('web_search_incognito', 1.2)),
    ({'search', 'private'}, ('web_search_incognito', 1.1)),
    ({'go', 'to'}, ('web_open_site_smart', 1.0)),
    ({'goto'}, ('web_open_site_smart', 0.9)),
    ({'site', 'open'}, ('web_open_site_smart', 0.9)),
    ({'time', 'response'}, ('b2_response_time', 1.0)),
    ({'site', 'speed'}, ('b2_response_time', 1.0)),
    ({'web', 'check'}, ('b2_webcheck', 1.0)),
    ({'create', 'folder'}, ('fs_mkdir', 1.0)),
    ({'make', 'folder'}, ('fs_mkdir', 1.0)),
    ({'new', 'folder'}, ('fs_mkdir', 1.0)),
    ({'mkdir'}, ('fs_mkdir', 1.0)),
    ({'file', 'create'}, ('fs_touch', 1.0)),
    ({'file', 'new'}, ('fs_touch', 1.0)),
    ({'touch'}, ('fs_touch', 1.0)),
    ({'symlink', 'create'}, ('fs_symlink', 1.0)),
    ({'file', 'delete'}, ('fs_del_file', 1.0)),
    ({'file', 'remove'}, ('fs_del_file', 1.0)),
    ({'folder', 'delete'}, ('fs_del_dir', 1.0)),
    ({'folder', 'remove'}, ('fs_del_dir', 1.0)),
    ({'organize', 'downloads'}, ('fs_org_dl', 1.0)),
    ({'downloads', 'sort'}, ('fs_org_dl', 1.0)),
    ({'file', 'copy'}, ('fs_cp_file', 1.0)),
    ({'move', 'file'}, ('fs_mv_file', 1.0)),
    ({'rename'}, ('fs_rename', 1.0)),
    ({'folder', 'copy'}, ('fs_cp_dir', 1.0)),
    ({'move', 'folder'}, ('fs_mv_dir', 1.0)),
    ({'file', 'open'}, ('fs_open', 1.0)),
    ({'reveal'}, ('fs_open_loc', 0.9)),
    ({'backup'}, ('fs_backup', 0.9)),
    ({'file', 'info'}, ('fs_info', 1.0)),
    ({'details', 'file'}, ('fs_info', 1.0)),
    ({'search', 'files'}, ('fs_search', 1.0)),
    ({'find', 'files'}, ('fs_search', 1.0)),
    ({'files', 'list'}, ('fs_ls', 1.0)),
    ({'ls'}, ('fs_ls', 1.0)),
    ({'dir'}, ('fs_ls', 0.9)),
    ({'recent', 'files'}, ('fs_recent', 1.0)),
    ({'size', 'folder'}, ('fs_size', 1.0)),
    ({'zip'}, ('fs_zip', 1.0)),
    ({'compress'}, ('fs_zip', 0.8)),
    ({'unzip'}, ('fs_unzip', 1.0)),
    ({'extract'}, ('fs_unzip', 0.8)),
    ({'executable', 'make'}, ('fs_make_exec', 1.0)),
    ({'chmod'}, ('fs_make_exec', 1.0)),
    ({'grep'}, ('fs_grep', 1.0)),
    ({'search', 'text'}, ('fs_grep', 1.0)),
    ({'read', 'file'}, ('fs_read', 1.0)),
    ({'cat'}, ('fs_read', 1.0)),
    ({'tail'}, ('fs_tail', 1.0)),
    ({'files', 'count'}, ('fs_count', 1.0)),
    ({'compare', 'files'}, ('fs_compare', 1.0)),
    ({'absolute', 'path'}, ('fs_abspath', 1.0)),
    ({'text', 'replace'}, ('fs_replace_text', 1.0)),
    ({'watch', 'file'}, ('fs_watch', 1.0)),
    ({'disk', 'usage'}, ('fs_du', 1.0)),
    ({'checksum'}, ('dev_hash', 1.0)),
    ({'hash', 'file'}, ('dev_hash', 1.0)),
    ({'append'}, ('fs_append', 1.0)),
    ({'timer'}, ('p_timer', 1.0)),
    ({'timer', 'set'}, ('p_timer', 1.0)),
    ({'countdown'}, ('p_timer', 0.9)),
    ({'remind'}, ('p_remind', 1.0)),
    ({'reminder'}, ('p_remind', 1.0)),
    ({'pomodoro'}, ('p_pomodoro', 1.0)),
    ({'timer', 'focus'}, ('p_pomodoro', 1.0)),
    ({'calculate'}, ('p_calc', 1.0)),
    ({'math'}, ('p_calc', 0.8)),
    ({'convert'}, ('p_convert', 0.8)),
    ({'random', 'number'}, ('p_rng', 1.0)),
    ({'dice', 'roll'}, ('fun_dice', 1.0)),
    ({'password'}, ('p_password', 0.9)),
    ({'generate', 'password'}, ('p_password', 1.0)),
    ({'note', 'add'}, ('p_note_add', 1.0)),
    ({'note'}, ('p_note_add_structured', 1.0)),
    ({'show', 'notes'}, ('p_notes_read', 1.0)),
    ({'notes', 'my'}, ('p_notes_read', 1.0)),
    ({'clear', 'notes'}, ('p_notes_clear', 1.0)),
    ({'note', 'read'}, ('p_note_read', 1.0)),
    ({'note', 'delete'}, ('p_note_delete', 1.0)),
    ({'list', 'notes'}, ('p_notes_list', 1.0)),
    ({'list', 'notes'}, ('p_notes_list', 1.0)),
    ({'on', 'turn', 'bluetooth'}, ('sys_bt_on', 1.2)),
    ({'enable', 'bluetooth'}, ('sys_bt_on', 1.2)),
    ({'on', 'bluetooth'}, ('sys_bt_on', 1.1)),
    ({'off', 'turn', 'bluetooth'}, ('sys_bt_off', 1.2)),
    ({'bluetooth', 'disable'}, ('sys_bt_off', 1.2)),
    ({'off', 'bluetooth'}, ('sys_bt_off', 1.1)),
    ({'on', 'turn', 'wifi'}, ('sys_wifi_on', 1.2)),
    ({'enable', 'wifi'}, ('sys_wifi_on', 1.2)),
    ({'on', 'wifi'}, ('sys_wifi_on', 1.1)),
    ({'off', 'wifi', 'turn'}, ('sys_wifi_off', 1.2)),
    ({'wifi', 'disable'}, ('sys_wifi_off', 1.2)),
    ({'off', 'wifi'}, ('sys_wifi_off', 1.1)),
    ({'startup', 'add'}, ('sys_add_startup', 1.0)),
    ({'startup', 'add'}, ('sys_add_startup', 1.0)),
    ({'startup', 'remove'}, ('sys_remove_startup', 1.0)),
    ({'startup', 'remove'}, ('sys_remove_startup', 1.0)),
    ({'startup', 'disable'}, ('sys_remove_startup', 1.0)),
    ({'enable', 'startup'}, ('sys_add_startup', 1.0)),
    ({'journal'}, ('p_journal', 1.0)),
    ({'diary'}, ('p_journal', 0.9)),
    ({'read', 'journal'}, ('p_journal_read', 1.0)),
    ({'add', 'todo'}, ('p_todo_add', 1.0)),
    ({'todo'}, ('p_todo_add', 0.8)),
    ({'task'}, ('p_todo_add', 0.7)),
    ({'todos', 'show'}, ('p_todo_show', 1.0)),
    ({'list', 'todo'}, ('p_todo_show', 1.0)),
    ({'todos', 'clear'}, ('p_todo_clear', 1.0)),
    ({'add', 'habit'}, ('p_habit_add', 1.0)),
    ({'habits', 'show'}, ('p_habit_show', 1.0)),
    ({'stopwatch'}, ('p2_stopwatch', 1.0)),
    ({'lorem', 'ipsum'}, ('p2_lorem', 1.0)),
    ({'word', 'count'}, ('p2_wordcount', 1.0)),
    ({'count', 'words'}, ('p2_wordcount', 1.0)),
    ({'count', 'char'}, ('p2_charcount', 1.0)),
    ({'reading', 'time'}, ('p2_reading_time', 1.0)),
    ({'qr', 'code'}, ('p2_qr_code', 1.0)),
    ({'qr', 'generate'}, ('p2_qr_code', 1.0)),
    ({'clipboard', 'read'}, ('p2_clip_read', 1.0)),
    ({'clipboard'}, ('p2_clip_read', 0.8)),
    ({'working', 'directory'}, ('p2_clip_pwd', 1.0)),
    ({'current', 'directory'}, ('p2_clip_pwd', 1.0)),
    ({'pwd'}, ('p2_clip_pwd', 1.0)),
    ({'percentage'}, ('p2_percentage', 1.0)),
    ({'percent', 'of'}, ('p2_percentage', 1.0)),
    ({'week', 'number'}, ('p2_weeknum', 1.0)),
    ({'status', 'git'}, ('dev_git_status', 1.0)),
    ({'pull', 'git'}, ('dev_git_pull', 1.0)),
    ({'push', 'git'}, ('dev_git_push', 1.0)),
    ({'log', 'git'}, ('dev_git_log', 1.0)),
    ({'diff', 'git'}, ('dev_git_diff', 1.0)),
    ({'stash', 'git'}, ('dev_git_stash', 1.0)),
    ({'pop', 'stash', 'git'}, ('dev_git_stash_pop', 1.0)),
    ({'branch', 'git'}, ('dev_git_branch', 1.0)),
    ({'init', 'git'}, ('dev_git_init', 1.0)),
    ({'commit', 'git'}, ('dev_git_commit', 1.0)),
    ({'add', 'git'}, ('dev_git_add', 1.0)),
    ({'checkout', 'git'}, ('dev_git_checkout', 1.0)),
    ({'merge', 'git'}, ('dev_git_merge', 1.0)),
    ({'tag', 'git'}, ('dev_git_tag', 1.0)),
    ({'remote', 'git'}, ('dev_git_remote', 1.0)),
    ({'clone', 'git'}, ('dev_git_clone', 1.0)),
    ({'reset', 'git'}, ('dev_git_reset', 1.0)),
    ({'npm', 'install'}, ('dev_npm_install', 1.0)),
    ({'npm', 'start'}, ('dev_npm_start', 1.0)),
    ({'npm', 'test'}, ('dev_npm_test', 1.0)),
    ({'npm', 'build'}, ('dev_npm_build', 1.0)),
    ({'npm', 'run'}, ('dev_npm_run', 1.0)),
    ({'outdated', 'npm'}, ('dev_npm_outdated', 1.0)),
    ({'npm', 'list'}, ('dev_npm_list', 1.0)),
    ({'ps', 'docker'}, ('dev_docker_ps', 1.0)),
    ({'images', 'docker'}, ('dev_docker_images', 1.0)),
    ({'docker', 'start'}, ('dev_docker_start', 1.0)),
    ({'docker', 'stop'}, ('dev_docker_stop', 1.0)),
    ({'docker', 'pull'}, ('dev_docker_pull', 1.0)),
    ({'docker', 'logs'}, ('dev_docker_logs', 1.0)),
    ({'rm', 'docker'}, ('dev_docker_rm', 1.0)),
    ({'build', 'docker'}, ('dev_docker_build', 1.0)),
    ({'run', 'python'}, ('dev_run_py', 1.0)),
    ({'script', 'run'}, ('dev_run_sh', 1.0)),
    ({'http', 'server'}, ('dev_http_serve', 1.0)),
    ({'serve'}, ('dev_http_serve', 0.8)),
    ({'install', 'pip'}, ('dev_pip_install', 1.0)),
    ({'list', 'pip'}, ('dev_pip_list', 1.0)),
    ({'freeze', 'pip'}, ('dev_pip_freeze', 1.0)),
    ({'update', 'pip'}, ('dev_pip_update', 1.0)),
    ({'apt', 'install'}, ('dev_apt_install', 1.0)),
    ({'update', 'apt'}, ('dev_apt_update', 1.0)),
    ({'apt', 'remove'}, ('dev_apt_remove', 1.0)),
    ({'version', 'python'}, ('dev_ver_py', 1.0)),
    ({'node', 'version'}, ('dev_ver_node', 1.0)),
    ({'version', 'git'}, ('dev_ver_git', 1.0)),
    ({'project', 'open'}, ('dev_open_proj', 1.0)),
    ({'create', 'venv'}, ('dev_venv', 1.0)),
    ({'uuid'}, ('dev_uuid', 1.0)),
    ({'generate', 'uuid'}, ('dev_uuid', 1.0)),
    ({'encode', 'base64'}, ('dev_b64enc', 1.0)),
    ({'decode', 'base64'}, ('dev_b64dec', 1.0)),
    ({'encode', 'base64'}, ('dev_b64enc', 1.0)),
    ({'decode', 'base64'}, ('dev_b64dec', 1.0)),
    ({'format', 'python'}, ('dev_py_format', 1.0)),
    ({'lint'}, ('dev_py_lint', 1.0)),
    ({'pytest'}, ('dev_pytest', 1.0)),
    ({'run', 'tests'}, ('dev_pytest', 1.0)),
    ({'make'}, ('dev_make', 1.0)),
    ({'gitignore'}, ('dev_gitignore', 1.0)),
    ({'format', 'json'}, ('dev_json_format', 1.0)),
    ({'port', 'check'}, ('dev_port_check', 1.0)),
    ({'port', 'check'}, ('dev_port_check', 1.0)),
    ({'localhost'}, ('dev_localhost', 1.0)),
    ({'process', 'kill'}, ('si_proc_kill', 1.0)),
    ({'ssh', 'generate'}, ('sec_ssh_keygen', 1.0)),
    ({'ssh', 'keygen'}, ('sec_ssh_keygen', 1.0)),
    ({'ssh', 'show'}, ('sec_show_ssh', 1.0)),
    ({'public', 'key'}, ('sec_show_ssh', 1.0)),
    ({'shred'}, ('sec_shred', 1.0)),
    ({'delete', 'secure'}, ('sec_shred', 1.0)),
    ({'cron'}, ('si2_cron_list', 1.0)),
    ({'crontab'}, ('si2_cron_list', 1.0)),
    ({'env', 'vars'}, ('dev_env_vars', 1.0)),
    ({'environment', 'variables'}, ('dev_env_vars', 1.0)),
    ({'validate', 'json'}, ('tt_json_validate', 1.0)),
    ({'validate', 'json'}, ('tt_json_validate', 1.0)),
    ({'encode', 'url'}, ('tt_url_encode', 1.0)),
    ({'encode', 'url'}, ('tt_url_encode', 1.0)),
    ({'decode', 'url'}, ('tt_url_decode', 1.0)),
    ({'decode', 'url'}, ('tt_url_decode', 1.0)),
    ({'html', 'encode'}, ('tt_html_encode', 1.0)),
    ({'html', 'decode'}, ('tt_html_decode', 1.0)),
    ({'rot13'}, ('tt_rot13', 1.0)),
    ({'slugify'}, ('tt_slugify', 1.0)),
    ({'camel', 'case'}, ('tt_camel', 1.0)),
    ({'snake', 'case'}, ('tt_snake', 1.0)),
    ({'uppercase'}, ('tt_upper', 1.0)),
    ({'lowercase'}, ('tt_lower', 1.0)),
    ({'lines', 'sort'}, ('tt_sort_lines', 1.0)),
    ({'unique', 'lines'}, ('tt_unique_lines', 1.0)),
    ({'duplicates', 'remove'}, ('tt_unique_lines', 1.0)),
    ({'reverse'}, ('tt_reverse', 0.8)),
    ({'extract', 'emails'}, ('tt_extract_emails', 1.0)),
    ({'extract', 'urls'}, ('tt_extract_urls', 1.0)),
    ({'palindrome'}, ('tt_palindrome', 1.0)),
    ({'word', 'frequency'}, ('tt_word_freq', 1.0)),
    ({'word', 'freq'}, ('tt_word_freq', 1.0)),
    ({'title', 'case'}, ('tt_title', 1.0)),
    ({'sentence', 'case'}, ('tt_sentence', 1.0)),
    ({'char', 'frequency'}, ('tt_char_freq', 1.0)),
    ({'prime'}, ('me_is_prime', 0.9)),
    ({'is', 'prime'}, ('me_is_prime', 1.0)),
    ({'fibonacci'}, ('me_fibonacci', 1.0)),
    ({'factorial'}, ('me_factorial', 1.0)),
    ({'gcd'}, ('me_gcd_lcm', 1.0)),
    ({'lcm'}, ('me_gcd_lcm', 1.0)),
    ({'prime', 'factors'}, ('me_prime_factors', 1.0)),
    ({'statistics'}, ('me_stats', 1.0)),
    ({'bmi'}, ('me_bmi', 1.0)),
    ({'interest', 'compound'}, ('me_compound', 1.0)),
    ({'tip'}, ('me_tip', 1.0)),
    ({'mortgage'}, ('me_mortgage', 1.0)),
    ({'convert', 'base'}, ('me_base_conv', 1.0)),
    ({'data', 'size'}, ('me_data_size', 1.0)),
    ({'solve'}, ('me_solve', 1.0)),
    ({'equation'}, ('me_solve', 0.9)),
    ({'simplify'}, ('me_simplify', 1.0)),
    ({'derivative'}, ('me_derivative', 1.0)),
    ({'integral'}, ('me_integral', 1.0)),
    ({'matrix'}, ('me_matrix', 1.0)),
    ({'quadratic'}, ('me_quadratic', 1.0)),
    ({'strength', 'password'}, ('se_pw_strength', 1.0)),
    ({'password', 'check'}, ('se_pw_strength', 1.0)),
    ({'passphrase'}, ('se_passphrase', 1.0)),
    ({'passphrase', 'generate'}, ('se_passphrase', 1.0)),
    ({'hash'}, ('se_hash_text', 0.9)),
    ({'encrypt'}, ('se_encrypt', 1.0)),
    ({'decrypt'}, ('se_decrypt', 1.0)),
    ({'failed', 'logins'}, ('se_failed_logins', 1.0)),
    ({'login', 'attempts'}, ('se_failed_logins', 1.0)),
    ({'weather'}, ('wn_weather', 1.0)),
    ({'forecast'}, ('wn_weather', 0.9)),
    ({'phase', 'moon'}, ('wn_moon_phase', 1.0)),
    ({'moon'}, ('wn_moon_phase', 0.8)),
    ({'crypto'}, ('wn_crypto', 0.9)),
    ({'bitcoin'}, ('wn_crypto', 1.0)),
    ({'rate', 'exchange'}, ('wn_exchange', 1.0)),
    ({'currency'}, ('wn_exchange', 0.8)),
    ({'news'}, ('wn_news', 1.0)),
    ({'headlines'}, ('wn_news', 0.9)),
    ({'stock'}, ('wn_stock', 0.9)),
    ({'info', 'ip'}, ('wn_ipinfo', 1.0)),
    ({'play'}, ('mm_play', 0.8)),
    ({'pause'}, ('mm_play', 0.9)),
    ({'track', 'next'}, ('mm_next', 1.0)),
    ({'next', 'song'}, ('mm_next', 1.0)),
    ({'track', 'previous'}, ('mm_prev', 1.0)),
    ({'song', 'previous'}, ('mm_prev', 1.0)),
    ({'webcam', 'photo'}, ('mm_webcam_photo', 1.0)),
    ({'photo', 'take'}, ('mm_webcam_photo', 1.0)),
    ({'download', 'youtube'}, ('mm_yt_video', 1.0)),
    ({'youtube', 'download'}, ('mm_yt_video', 1.0)),
    ({'convert', 'image'}, ('mm_img_convert', 1.0)),
    ({'image', 'resize'}, ('mm_img_resize', 1.0)),
    ({'image', 'info'}, ('mm_img_info', 1.0)),
    ({'record', 'audio'}, ('m2_record_audio', 1.0)),
    ({'screen', 'record'}, ('m2_record_screen', 1.0)),
    ({'screen', 'record'}, ('m2_record_screen', 1.0)),
    ({'play', 'file'}, ('m2_play_file', 1.0)),
    ({'files', 'large'}, ('cl_find_large', 1.0)),
    ({'find', 'large'}, ('cl_find_large', 1.0)),
    ({'empty', 'files'}, ('cl_find_empty', 1.0)),
    ({'hidden', 'files'}, ('cl_find_hidden', 1.0)),
    ({'tree'}, ('cl_tree', 1.0)),
    ({'find', 'old'}, ('cl_find_old', 1.0)),
    ({'files', 'old'}, ('cl_find_old', 1.0)),
    ({'duplicates'}, ('cl_find_duplicates', 1.0)),
    ({'clean', 'apt'}, ('cl_apt_clean', 1.0)),
    ({'memory', 'free'}, ('cl_free_mem', 1.0)),
    ({'ram', 'clear'}, ('cl_free_mem', 1.0)),
    ({'joke'}, ('fun_joke', 1.0)),
    ({'joke', 'tell'}, ('fun_joke', 1.0)),
    ({'funny'}, ('fun_joke', 0.7)),
    ({'fact'}, ('fun_fact', 0.8)),
    ({'random', 'fact'}, ('fun_fact', 1.0)),
    ({'fun', 'fact'}, ('fun_fact', 1.0)),
    ({'quote'}, ('fun_quote', 1.0)),
    ({'inspire'}, ('fun_quote', 0.9)),
    ({'motivation'}, ('fun_quote', 0.9)),
    ({'affirmation'}, ('fun_affirm', 1.0)),
    ({'motivate', 'me'}, ('fun_affirm', 1.0)),
    ({'word', 'day'}, ('fun_word', 1.0)),
    ({'word', 'day', 'of'}, ('fun_word', 1.0)),
    ({'coin'}, ('fun_coin', 0.9)),
    ({'flip', 'coin'}, ('fun_coin', 1.0)),
    ({'tails', 'heads'}, ('fun_coin', 1.0)),
    ({'dice'}, ('fun_dice', 0.9)),
    ({'magic', '8'}, ('fun_magic8', 1.0)),
    ({'ball', 'eight'}, ('fun_magic8', 1.0)),
    ({'greet'}, ('fun_greet', 0.9)),
    ({'hello'}, ('fun_greet', 0.6)),
    ({'morning', 'good'}, ('fun_greet', 1.0)),
    ({'afternoon', 'good'}, ('fun_greet', 1.0)),
    ({'evening', 'good'}, ('fun_greet', 1.0)),
    ({'todos', 'my'}, ('p_todo_show', 1.0)),
    ({'habits', 'my'}, ('p_habit_show', 1.0)),
    ({'tasks', 'my'}, ('p_todo_show', 1.0)),
    ({'task', 'list'}, ('p_todo_show', 1.0)),
    ({'i', 'am', 'who'}, ('si2_whoami', 1.0)),
    ({'log', 'system'}, ('si2_syslog', 1.0)),
    ({'logged', 'who'}, ('si2_last_logins', 1.0)),
    ({'download'}, ('net_download', 0.8)),
    ({'network', 'scan'}, ('net_scan_local', 1.0)),
    ({'download', 'speed'}, ('net_speed', 1.0)),
    ({'riddle'}, ('fun_riddle', 1.0)),
    ({'trivia'}, ('fun_trivia', 1.0)),
    ({'enable', 'nova'}, ('nova_on', 1.0)),
    ({'on', 'nova'}, ('nova_on', 1.0)),
    ({'nova', 'disable'}, ('nova_off', 1.0)),
    ({'off', 'nova'}, ('nova_off', 1.0)),
    ({'status', 'nova'}, ('nova_status', 1.0)),
    ({'info', 'nova'}, ('nova_status', 1.0)),
    ({'clear', 'nova'}, ('nova_clear', 1.0)),
    ({'install', 'gemini'}, ('nova_install_gemini', 1.0)),
    ({'install', 'nova'}, ('nova_install_gemini', 1.0)),
    ({'install', 'nova'}, ('nova_install_gemini', 1.0)),
    ({'browser', 'set'}, ('cfg_set_browser', 1.0)),
    ({'search', 'set'}, ('cfg_set_search', 1.0)),
    ({'theme', 'set'}, ('cfg_set_theme', 1.0)),
    ({'ai', 'set'}, ('cfg_set_ai', 1.0)),
    ({'stt', 'set'}, ('cfg_set_stt', 1.0)),
    ({'status', 'stt'}, ('cfg_show_stt', 1.0)),
    ({'google', 'stt', 'set'}, ('cfg_set_stt', 1.2)),
    ({'stt', 'vosk', 'set'}, ('cfg_set_stt', 1.2)),
    ({'stt', 'offline', 'set'}, ('cfg_set_stt', 1.2)),
    ({'online', 'stt', 'set'}, ('cfg_set_stt', 1.2)),
    ({'stt', 'set', 'auto'}, ('cfg_set_stt', 1.2)),
    ({'stt', 'toggle'}, ('cfg_toggle_stt', 1.0)),
    ({'switch', 'stt'}, ('cfg_toggle_stt', 1.0)),
    ({'stt', 'show'}, ('cfg_show_stt', 1.0)),
    ({'mics', 'list'}, ('cfg_list_mics', 1.0)),
    ({'list', 'microphones'}, ('cfg_list_mics', 1.0)),
    ({'mics', 'show'}, ('cfg_list_mics', 1.0)),
    ({'list', 'mic'}, ('cfg_list_mics', 1.0)),
    ({'set', 'mic'}, ('cfg_set_mic', 1.0)),
    ({'microphone', 'set'}, ('cfg_set_mic', 1.0)),
    ({'energy', 'set'}, ('cfg_set_energy', 1.0)),
    ({'set', 'dynamic'}, ('cfg_set_dynamic', 1.1)),
    ({'on', 'dynamic'}, ('cfg_set_dynamic', 1.3)),
    ({'off', 'dynamic'}, ('cfg_set_dynamic', 1.3)),
    ({'toggle', 'dynamic'}, ('cfg_set_dynamic', 1.2)),
    ({'energy', 'dynamic'}, ('cfg_set_dynamic', 1.0)),
    ({'threshold', 'dynamic'}, ('cfg_set_dynamic', 1.0)),
    ({'test', 'mic'}, ('cfg_test_mic', 1.0)),
    ({'microphone', 'test'}, ('cfg_test_mic', 1.0)),
    ({'test', 'mic'}, ('cfg_test_mic', 1.0)),
    ({'doctor', 'voice'}, ('cfg_test_mic', 1.0)),
    ({'voice', 'diagnostic'}, ('cfg_test_mic', 1.0)),
    ({'voice', 'test'}, ('cfg_test_mic', 1.0)),
    ({'voice', 'test'}, ('cfg_test_mic', 1.0)),
    ({'speech', 'test'}, ('cfg_test_mic', 1.0)),
    ({'stt', 'test'}, ('cfg_test_mic', 1.0)),
    ({'diagnose', 'mic'}, ('cfg_test_mic', 1.0)),
    ({'diagnose', 'voice'}, ('cfg_test_mic', 1.0)),
    ({'ai', 'default'}, ('cfg_show_ai', 1.0)),
    ({'toggle', 'tts'}, ('cfg_toggle_tts', 1.3)),
    ({'voice', 'toggle'}, ('cfg_toggle_tts', 1.2)),
    ({'voice', 'mute'}, ('cfg_toggle_tts', 1.2)),
    ({'unmute', 'voice'}, ('cfg_toggle_tts', 1.2)),
    ({'voice', 'output'}, ('cfg_toggle_tts', 1.1)),
    ({'list', 'bookmarks'}, ('mm_show_bookmarks', 1.3)),
    ({'show', 'bookmarks'}, ('mm_show_bookmarks', 1.3)),
    ({'bookmarks', 'my'}, ('mm_show_bookmarks', 1.3)),
    ({'add', 'bookmark'}, ('mm_add_bookmark', 1.3)),
    ({'bookmark', 'delete'}, ('mm_del_bookmark', 1.3)),
    ({'bookmark', 'remove'}, ('mm_del_bookmark', 1.3)),
    ({'list', 'software'}, ('mm_list_software', 1.3)),
    ({'software', 'show'}, ('mm_list_software', 1.3)),
    ({'software', 'my'}, ('mm_list_software', 1.3)),
    ({'yolo', 'toggle'}, ('cfg_toggle_yolo', 1.0)),
    ({'api', 'set', 'key'}, ('cfg_set_api_key', 1.0)),
    ({'show', 'config'}, ('cfg_show', 1.0)),
    ({'todos', 'my'}, ('p_todo_show', 1.0)),
    ({'habits', 'my'}, ('p_habit_show', 1.0)),
    ({'tasks', 'my'}, ('p_todo_show', 1.0)),
    ({'task', 'list'}, ('p_todo_show', 1.0)),
    ({'i', 'am', 'who'}, ('si2_whoami', 1.0)),
    ({'log', 'system'}, ('si2_syslog', 1.0)),
    ({'logged', 'who'}, ('si2_last_logins', 1.0)),
    ({'settings'}, ('cfg_show', 1.0)),
    ({'days', 'left', 'year'}, ('p2_days_left_year', 1.0)),
    ({'how', 'old'}, ('p2_age_calc', 1.0)),
    ({'age', 'my'}, ('p2_age_calc', 1.0)),
    ({'difference', 'time'}, ('p2_time_diff', 1.0)),
    ({'leap', 'year'}, ('p2_leap_year', 1.0)),
    ({'days', 'month'}, ('p2_month_days', 1.0)),
    ({'days', 'business'}, ('p2_biz_days', 1.0)),
    ({'days', 'add'}, ('p2_add_days', 1.0)),
    ({'next', 'monday'}, ('p2_next_weekday', 1.0)),
    ({'friday', 'next'}, ('p2_next_weekday', 1.0)),
    ({'next', 'weekend'}, ('p2_next_weekday', 1.0)),
    ({'processes', 'top'}, ('si_proc_list', 1.0)),
    ({'info', 'cpu'}, ('si_cpu', 1.0)),
    ({'screen', 'resolution'}, ('si2_resolution', 1.0)),
    ({'devices', 'audio'}, ('si2_audio', 1.0)),
    ({'pci', 'devices'}, ('si2_lspci', 1.0)),
    ({'locale'}, ('si2_locale', 1.0)),
    ({'timezone', 'info'}, ('si2_tz', 1.0)),
    ({'io', 'stats'}, ('si2_iostat', 1.0)),
    ({'files', 'open'}, ('si2_open_files', 1.0)),
    ({'hardware', 'info'}, ('si2_summary', 1.0)),
    ({'network', 'scan'}, ('net_scan_local', 1.0)),
    ({'download', 'speed'}, ('net_speed', 1.0)),
    ({'upload', 'speed'}, ('net_speed', 1.0)),
    ({'address', 'mac'}, ('net_mac', 1.0)),
    ({'table', 'route'}, ('net_routes', 1.0)),
    ({'status', 'vpn'}, ('net_vpn', 1.0)),
    ({'bandwidth'}, ('net_speed', 0.9)),
    ({'download'}, ('net_download', 0.8)),
    ({'permissions', 'file'}, ('fs_perms', 1.0)),
    ({'file', 'split'}, ('fs_split', 1.0)),
    ({'files', 'join'}, ('fs_join', 1.0)),
    ({'file', 'encrypt'}, ('fs_encrypt_file', 1.0)),
    ({'file', 'decrypt'}, ('fs_decrypt_file', 1.0)),
    ({'type', 'file'}, ('fs_mime_type', 1.0)),
    ({'type', 'mime'}, ('fs_mime_type', 1.0)),
    ({'find', 'symlinks'}, ('fs_find_symlinks', 1.0)),
    ({'files', 'size', 'sort'}, ('fs_sort_size', 1.0)),
    ({'rename', 'batch'}, ('fs_batch_rename', 1.0)),
    ({'search', 'word'}, ('fs_grep', 0.9)),
    ({'graph', 'git'}, ('dev_git_graph', 1.0)),
    ({'blame', 'git'}, ('dev_git_blame', 1.0)),
    ({'show', 'git'}, ('dev_git_show', 1.0)),
    ({'undo', 'git'}, ('dev_git_undo', 1.0)),
    ({'amend', 'git'}, ('dev_git_amend', 1.0)),
    ({'whoami', 'git'}, ('dev_git_whoami', 1.0)),
    ({'config', 'git'}, ('dev_git_cfg', 1.0)),
    ({'fetch', 'git'}, ('dev_git_fetch', 1.0)),
    ({'stash', 'git'}, ('dev_git_stash', 1.0)),
    ({'branches', 'git'}, ('dev_git_branches', 1.0)),
    ({'tags', 'git'}, ('dev_git_tags', 1.0)),
    ({'remote', 'git'}, ('dev_git_remote', 1.0)),
    ({'npm', 'audit'}, ('dev_npm_audit', 1.0)),
    ({'stats', 'docker'}, ('dev_docker_stats', 1.0)),
    ({'docker', 'prune'}, ('dev_docker_prune', 1.0)),
    ({'exec', 'docker'}, ('dev_docker_exec', 1.0)),
    ({'packages', 'list'}, ('dev_pip_list', 1.0)),
    ({'find', 'todos'}, ('dev_find_todos', 1.0)),
    ({'lines', 'count'}, ('dev_count_lines', 1.0)),
    ({'regex', 'test'}, ('dev_regex_test', 1.0)),
    ({'decode', 'jwt'}, ('dev_jwt_decode', 1.0)),
    ({'yaml', 'to', 'json'}, ('dev_json2yaml', 1.0)),
    ({'yaml', 'to', 'json'}, ('dev_yaml2json', 1.0)),
    ({'csv', 'to', 'json'}, ('dev_csv2json', 1.0)),
    ({'which'}, ('dev_which', 1.0)),
    ({'project', 'create'}, ('dev_new_project', 1.0)),
    ({'requirements', 'generate'}, ('dev_gen_reqs', 1.0)),
    ({'generate', 'dockerfile'}, ('dev_gen_docker', 1.0)),
    ({'benchmark'}, ('dev_benchmark', 1.0)),
    ({'profile', 'python'}, ('dev_profile', 1.0)),
    ({'mypy'}, ('dev_mypy', 1.0)),
    ({'coverage'}, ('dev_coverage', 1.0)),
    ({'show', 'path'}, ('dev_show_path', 1.0)),
    ({'square', 'root'}, ('me_sqrt', 1.0)),
    ({'sqrt'}, ('me_sqrt', 1.0)),
    ({'cube', 'root'}, ('me_cbrt', 1.0)),
    ({'pi'}, ('me_pi', 1.0)),
    ({'ratio', 'golden'}, ('me_golden', 1.0)),
    ({'logarithm'}, ('me_log', 1.0)),
    ({'sin'}, ('me_trig', 1.0)),
    ({'cos'}, ('me_trig', 1.0)),
    ({'tan'}, ('me_trig', 1.0)),
    ({'trig'}, ('me_trig', 1.0)),
    ({'percentage', 'change'}, ('me_pct_change', 1.0)),
    ({'permutation'}, ('me_perm', 1.0)),
    ({'combination'}, ('me_comb', 1.0)),
    ({'list', 'prime'}, ('me_prime_list', 1.0)),
    ({'numeral', 'roman'}, ('me_roman', 1.0)),
    ({'roman'}, ('me_roman', 0.9)),
    ({'convert', 'temperature'}, ('me_temp_conv', 1.0)),
    ({'fahrenheit', 'celsius'}, ('me_temp_conv', 1.0)),
    ({'fahrenheit', 'celsius'}, ('me_temp_conv', 1.0)),
    ({'kelvin'}, ('me_temp_conv', 0.9)),
    ({'fuel', 'efficiency'}, ('me_fuel', 1.0)),
    ({'calories'}, ('me_calories', 0.9)),
    ({'polygon'}, ('me_polygon', 1.0)),
    ({'circle', 'area'}, ('me_circle', 1.0)),
    ({'circle', 'area'}, ('me_circle', 1.0)),
    ({'triangle', 'area'}, ('me_triangle', 1.0)),
    ({'random', 'between'}, ('p_rng', 1.0)),
    ({'morse', 'code'}, ('tt_morse', 1.0)),
    ({'decode', 'morse'}, ('tt_morse_decode', 1.0)),
    ({'alphabet', 'nato'}, ('tt_nato', 1.0)),
    ({'cipher', 'caesar'}, ('tt_caesar', 1.0)),
    ({'binary', 'text'}, ('tt_bin_text', 1.0)),
    ({'binary', 'text', 'to'}, ('tt_text_bin', 1.0)),
    ({'binary', 'text'}, ('tt_text_bin', 1.0)),
    ({'binary', 'encode'}, ('tt_text_bin', 1.0)),
    ({'convert', 'binary'}, ('tt_text_bin', 1.0)),
    ({'decode', 'hex'}, ('tt_hex_text', 1.0)),
    ({'decode', 'hex'}, ('tt_hex_text', 1.0)),
    ({'from', 'hex'}, ('tt_hex_text', 1.0)),
    ({'text', 'hex'}, ('tt_hex_text', 0.6)),
    ({'text', 'hex'}, ('tt_text_hex', 1.0)),
    ({'ascii', 'art'}, ('tt_ascii_art', 1.0)),
    ({'bold', 'text'}, ('tt_bold_text', 1.0)),
    ({'lines', 'number'}, ('tt_num_lines', 1.0)),
    ({'prefix', 'add'}, ('tt_prefix_lines', 1.0)),
    ({'suffix', 'add'}, ('tt_suffix_lines', 1.0)),
    ({'text', 'wrap'}, ('tt_wrap', 1.0)),
    ({'center', 'text'}, ('tt_center', 1.0)),
    ({'anagram'}, ('tt_anagram', 1.0)),
    ({'pig', 'latin'}, ('tt_pig_latin', 1.0)),
    ({'minify', 'json'}, ('tt_json_minify', 1.0)),
    ({'spaces', 'remove'}, ('tt_rm_spaces', 1.0)),
    ({'extract', 'numbers'}, ('tt_extract_nums', 1.0)),
    ({'stats', 'text'}, ('p2_wordcount', 0.9)),
    ({'random', 'bytes'}, ('se_rand_bytes', 1.0)),
    ({'token', 'secure'}, ('se_rand_bytes', 1.0)),
    ({'otp'}, ('se_otp', 1.0)),
    ({'bcrypt'}, ('se_bcrypt', 1.0)),
    ({'hmac'}, ('se_hmac', 1.0)),
    ({'xor'}, ('se_xor', 1.0)),
    ({'hash', 'file'}, ('dev_hash', 1.0)),
    ({'compliment'}, ('fun_compliment', 1.0)),
    ({'me', 'roast'}, ('fun_roast', 1.0)),
    ({'fortune'}, ('fun_fortune', 1.0)),
    ({'haiku'}, ('fun_haiku', 1.0)),
    ({'poem'}, ('fun_poem', 1.0)),
    ({'story'}, ('fun_story', 1.0)),
    ({'random', 'name'}, ('fun_random_name', 1.0)),
    ({'color', 'random'}, ('fun_rand_color', 1.0)),
    ({'random', 'emoji'}, ('fun_rand_emoji', 1.0)),
    ({'fact', 'number'}, ('fun_num_fact', 1.0)),
    ({'on', 'this', 'day'}, ('fun_this_day', 1.0)),
    ({'cowsay'}, ('fun_cowsay', 1.0)),
    ({'twister', 'tongue'}, ('fun_tongue', 1.0)),
    ({'scissors', 'rock', 'paper'}, ('fun_rps', 1.0)),
    ({'joke', 'dad'}, ('fun_joke', 1.0)),
    ({'this', 'history', 'day'}, ('fun_this_day', 1.0)),
    ({'note', 'search'}, ('p_note_search', 1.0)),
    ({'search', 'notes'}, ('p_note_search', 1.0)),
    ({'done', 'todo'}, ('p_todo_done', 1.0)),
    ({'mark', 'done'}, ('p_todo_done', 1.0)),
    ({'todo', 'delete'}, ('p_todo_del', 1.0)),
    ({'todos', 'clear'}, ('p_todo_clear', 1.0)),
    ({'break', 'time'}, ('p_break', 1.0)),
    ({'break', 'take'}, ('p_break', 1.0)),
    ({'drink', 'water'}, ('p_water', 1.0)),
    ({'reminder', 'water'}, ('p_water', 1.0)),
    ({'goal', 'set'}, ('p_goal', 1.0)),
    ({'goals', 'show'}, ('p_goal_show', 1.0)),
    ({'gratitude'}, ('p_gratitude', 1.0)),
    ({'log', 'mood'}, ('p_mood', 1.0)),
    ({'mood'}, ('p_mood', 1.0)),
    ({'add', 'expense'}, ('p_expense', 1.0)),
    ({'expenses', 'show'}, ('p_exp_show', 1.0)),
    ({'total', 'expenses'}, ('p_exp_total', 1.0)),
    ({'budget'}, ('p_budget', 1.0)),
    ({'flash', 'cards'}, ('p_flashcard', 1.0)),
    ({'flashcard'}, ('p_flashcard', 1.0)),
    ({'flashcards'}, ('p_flashcard', 1.0)),
    ({'meeting', 'notes'}, ('p_meeting', 1.0)),
    ({'quiz'}, ('p_quiz', 1.0)),
    ({'hacker', 'news'}, ('web_hn', 1.0)),
    ({'github', 'trending'}, ('web_gh_trending', 1.0)),
    ({'wikipedia', 'open'}, ('web_wiki', 1.0)),
    ({'word', 'define'}, ('web_dictionary', 1.0)),
    ({'dictionary'}, ('web_dictionary', 1.0)),
    ({'thesaurus'}, ('web_thesaurus', 1.0)),
    ({'synonym'}, ('web_thesaurus', 0.9)),
    ({'dictionary', 'urban'}, ('web_urban', 1.0)),
    ({'google', 'trends'}, ('web_trends', 1.0)),
    ({'calendar', 'open'}, ('web_gcal', 1.0)),
    ({'google', 'drive'}, ('web_drive', 1.0)),
    ({'google', 'docs'}, ('web_gdocs', 1.0)),
    ({'google', 'sheets'}, ('web_gsheets', 1.0)),
    ({'figma', 'open'}, ('a2_figma', 1.0)),
    ({'canva', 'open'}, ('a2_canva', 1.0)),
    ({'notion', 'open'}, ('b2_notion', 1.0)),
    ({'trello', 'open'}, ('b2_trello', 1.0)),
    ({'jira'}, ('web_jira', 0.9)),
    ({'asana'}, ('web_asana', 0.9)),
    ({'vercel'}, ('web_vercel', 1.0)),
    ({'netlify'}, ('web_netlify', 1.0)),
    ({'aws', 'console'}, ('web_aws', 1.0)),
    ({'azure'}, ('web_azure', 0.9)),
    ({'leetcode'}, ('web_leetcode', 1.0)),
    ({'hackerrank'}, ('web_hackerrank', 1.0)),
    ({'medium'}, ('web_medium', 1.0)),
    ({'devto'}, ('web_devto', 1.0)),
    ({'twitch', 'open'}, ('web_twitch', 1.0)),
    ({'soundcloud'}, ('web_soundcloud', 1.0)),
    ({'translate', 'open'}, ('b2_translate', 1.0)),
    ({'news', 'bbc'}, ('web_bbc', 1.0)),
    ({'techcrunch'}, ('web_techcrunch', 1.0)),
    ({'verge', 'the'}, ('web_theverge', 1.0)),
    ({'wired'}, ('web_wired', 1.0)),
    ({'meet', 'open'}, ('web_meet', 1.0)),
    ({'slides', 'open'}, ('web_gslides', 1.0)),
    ({'codepen'}, ('web_codepen', 0.9)),
    ({'codesandbox'}, ('web_codesandbox', 1.0)),
    ({'stackblitz'}, ('web_stackblitz', 1.0)),
    ({'exercism'}, ('web_exercism', 1.0)),
    ({'codewars'}, ('web_codewars', 1.0)),
    ({'compress', 'image'}, ('mm_img_compress', 1.0)),
    ({'image', 'thumbnail'}, ('mm_img_thumb', 1.0)),
    ({'image', 'rotate'}, ('mm_img_rotate', 1.0)),
    ({'image', 'flip'}, ('mm_img_flip', 1.0)),
    ({'image', 'crop'}, ('mm_img_crop', 1.0)),
    ({'grayscale', 'image'}, ('mm_img_gray', 1.0)),
    ({'image', 'blur'}, ('mm_img_blur', 1.0)),
    ({'ocr'}, ('mm_img_ocr', 1.0)),
    ({'exif'}, ('mm_img_exif', 1.0)),
    ({'image', 'metadata'}, ('mm_img_exif', 0.9)),
    ({'images', 'list'}, ('mm_list_images', 1.0)),
    ({'ups', 'sit'}, ('p_exercise', 1.0)),
    ({'push', 'ups'}, ('p_exercise', 1.0)),
    ({'workout'}, ('p_exercise', 0.9)),
    ({'exercise'}, ('p_exercise', 0.9)),
    ({'today', 'steps'}, ('p_steps', 1.0)),
    ({'counter', 'step'}, ('p_steps', 1.0)),
    ({'sleep', 'tracker'}, ('p_sleep', 1.0)),
    ({'log', 'sleep'}, ('p_sleep', 1.0)),
    ({'bmi'}, ('me_bmi', 1.1)),
    ({'weight'}, ('me_bmi', 0.8)),
    ({'heart', 'rate'}, ('p_heart_rate', 1.0)),
    ({'pressure', 'blood'}, ('p_bp', 1.0)),
    ({'medication', 'reminder'}, ('p_med_reminder', 1.0)),
    ({'time', 'medicine'}, ('p_med_reminder', 1.0)),
    ({'bill', 'split'}, ('p_split_bill', 1.0)),
    ({'dutch'}, ('p_split_bill', 1.0)),
    ({'calculator', 'loan'}, ('me_loan', 1.0)),
    ({'emi'}, ('me_loan', 1.0)),
    ({'monthly', 'payment'}, ('me_loan', 0.9)),
    ({'goal', 'savings'}, ('p_savings', 1.0)),
    ({'calculator', 'interest'}, ('me_interest', 1.0)),
    ({'percentage', 'of'}, ('me_pct_of', 1.0)),
    ({'percent', 'what'}, ('me_pct_of', 0.9)),
    ({'discount'}, ('me_discount', 1.0)),
    ({'price', 'sale'}, ('me_discount', 0.9)),
    ({'tax'}, ('me_tax', 1.0)),
    ({'gst'}, ('me_tax', 0.9)),
    ({'vat'}, ('me_tax', 0.9)),
    ({'recipe'}, ('fun_recipe', 1.0)),
    ({'cooking'}, ('fun_recipe', 0.8)),
    ({'cooking', 'timer'}, ('p_cook_timer', 1.0)),
    ({'boil', 'eggs'}, ('p_boil_eggs', 1.0)),
    ({'grams', 'cups', 'to'}, ('me_cup_convert', 1.0)),
    ({'grams', 'cups', 'to'}, ('me_cup_convert', 1.0)),
    ({'cup', 'convert'}, ('me_cup_convert', 1.0)),
    ({'tablespoon'}, ('me_cup_convert', 0.8)),
    ({'teaspoon'}, ('me_cup_convert', 0.8)),
    ({'zone', 'time'}, ('p2_tz_convert', 1.0)),
    ({'timezone'}, ('p2_tz_convert', 0.9)),
    ({'convert', 'zone', 'time'}, ('p2_tz_convert', 1.0)),
    ({'flight', 'time'}, ('p2_flight_est', 1.0)),
    ({'time', 'travel'}, ('p2_flight_est', 0.9)),
    ({'distance', 'between'}, ('p2_distance', 1.0)),
    ({'distance', 'speed', 'time'}, ('me_sdt', 1.0)),
    ({'define'}, ('web_dictionary', 0.9)),
    ({'spelling'}, ('tt_spelling', 1.0)),
    ({'spell'}, ('tt_spelling', 0.9)),
    ({'grammar'}, ('tt_grammar', 1.0)),
    ({'translate'}, ('b2_translate_text', 0.9)),
    ({'acronym'}, ('tt_acronym', 1.0)),
    ({'abbreviation'}, ('tt_acronym', 0.9)),
    ({'alarm'}, ('p_alarm', 1.0)),
    ({'set', 'alarm'}, ('p_alarm', 1.0)),
    ({'countdown'}, ('p_countdown', 1.0)),
    ({'count', 'down'}, ('p_countdown', 1.0)),
    ({'reminders', 'show'}, ('p_reminders_show', 1.0)),
    ({'reminders', 'my'}, ('p_reminders_show', 1.0)),
    ({'reminders', 'clear'}, ('p_reminders_clear', 1.0)),
    ({'note', 'pad'}, ('p_notes_read', 0.9)),
    ({'note', 'quick'}, ('p_note_add_structured', 1.0)),
    ({'note', 'sticky'}, ('p_note_add_structured', 1.0)),
    ({'screen', 'time'}, ('si2_screen_time', 1.0)),
    ({'start', 'auto'}, ('si2_autostart', 1.0)),
    ({'startup', 'apps'}, ('si2_autostart', 0.9)),
    ({'apps', 'running'}, ('si_proc_list', 0.9)),
    ({'apps', 'active'}, ('si_proc_list', 0.9)),
    ({'clipboard'}, ('p_clipboard', 1.0)),
    ({'paste'}, ('p_clipboard', 0.8)),
    ({'clipboard', 'to', 'copy'}, ('p_clip_copy', 1.0)),
    ({'clipboard', 'history'}, ('p_clip_hist', 1.0)),
    ({'font', 'list'}, ('si2_fonts', 1.0)),
    ({'installed', 'fonts'}, ('si2_fonts', 0.9)),
    ({'email', 'draft'}, ('p_email_draft', 1.0)),
    ({'email', 'write'}, ('p_email_draft', 0.9)),
    ({'email', 'subject'}, ('p_email_draft', 0.9)),
    ({'sms', 'draft'}, ('p_sms_draft', 1.0)),
    ({'linkedin', 'message'}, ('p_linkedin', 1.0)),
    ({'kanban'}, ('p_kanban', 1.0)),
    ({'sprint'}, ('p_pomodoro', 0.9)),
    ({'up', 'stand'}, ('p_standup', 1.0)),
    ({'daily', 'standup'}, ('p_standup', 1.0)),
    ({'release', 'notes'}, ('dev_release_notes', 1.0)),
    ({'changelog'}, ('dev_release_notes', 0.9)),
    ({'commit', 'message'}, ('dev_commit_msg', 1.0)),
    ({'commit', 'write'}, ('dev_commit_msg', 0.9)),
    ({'nebula', 'mute'}, ('cfg_toggle_nebula_tts', 1.5)),
    ({'mute', 'nova'}, ('cfg_toggle_nova_tts', 1.5)),
    ({'voice', 'nebula'}, ('cfg_toggle_nebula_tts', 1.5)),
    ({'voice', 'nova'}, ('cfg_toggle_nova_tts', 1.5)),
    ({'speech', 'nebula', 'toggle'}, ('cfg_toggle_nebula_tts', 1.5)),
    ({'speech', 'toggle', 'nova'}, ('cfg_toggle_nova_tts', 1.5)),
    ({'confirm', 'nova'}, ('cfg_toggle_nova_confirm', 1.5)),
    ({'auto', 'nova'}, ('cfg_toggle_nova_confirm', 1.5)),
    ({'lorem', 'ipsum'}, ('p2_lorem', 1.0)),
    ({'placeholder', 'text'}, ('p2_lorem', 0.9)),
    ({'unix', 'time'}, ('p2_epoch', 1.1)),
    ({'timestamp'}, ('p2_epoch', 0.9)),
    ({'timezone', 'my'}, ('si2_tz', 1.0)),
    ({'world', 'time'}, ('p2_world_time', 1.0)),
    ({'in', 'time'}, ('p2_world_time', 1.0)),
    ({'rise', 'sun'}, ('p2_sunrise', 1.0)),
    ({'sunset'}, ('p2_sunrise', 1.0)),
    ({'phase', 'moon'}, ('p2_moonphase', 0.9)),
    ({'ascii', 'table'}, ('tt_ascii_table', 1.0)),
    ({'shortcut', 'keyboard'}, ('tt_shortcuts', 1.0)),
    ({'shortcuts'}, ('tt_shortcuts', 0.9)),
    ({'sheet', 'cheat'}, ('tt_shortcuts', 1.0)),
    ({'hotkey'}, ('tt_shortcuts', 0.9)),
    ({'network', 'speed'}, ('net_speed', 1.0)),
    ({'wifi', 'password'}, ('net_wifi_pass', 1.0)),
    ({'connected', 'devices'}, ('net_devices', 1.0)),
    ({'test', 'connection'}, ('net_ping_test', 1.0)),
    ({'internet', 'check'}, ('net_ping_test', 1.0)),
    ({'battery'}, ('si_battery', 1.0)),
    ({'status', 'battery'}, ('si_battery', 1.0)),
    ({'memory', 'usage'}, ('si_ram', 0.9)),
    ({'memory', 'free'}, ('si_ram', 0.9)),
    ({'usage', 'swap'}, ('si_swap', 1.0)),
    ({'temperature'}, ('si_temp', 1.0)),
    ({'temperature', 'cpu'}, ('si_temp', 1.0)),
    ({'fan', 'speed'}, ('si_temp', 0.9)),
    ({'random', 'number'}, ('fun_rand_num', 1.0)),
    ({'random', 'between'}, ('fun_rand_num', 1.0)),
    ({'pick', 'random'}, ('fun_rand_num', 0.9)),
    ({'random', 'choice'}, ('fun_rand_choice', 1.0)),
    ({'shuffle'}, ('fun_shuffle', 1.0)),
    ({'pick', 'from'}, ('fun_rand_choice', 1.0)),
    ({'roll'}, ('fun_dice', 0.9)),
    ({'dice'}, ('fun_dice', 1.0)),
    ({'flip', 'coin'}, ('fun_coin', 1.1)),
    ({'tails', 'heads'}, ('fun_coin', 1.1)),
    ({'word', 'wrap'}, ('tt_wrap', 0.9)),
    ({'vowels', 'count'}, ('tt_count_vowels', 1.0)),
    ({'consonants', 'count'}, ('tt_count_vowels', 0.9)),
    ({'is', 'palindrome'}, ('tt_palindrome', 1.0)),
    ({'palindrome', 'check'}, ('tt_palindrome', 1.0)),
    ({'reverse', 'text'}, ('tt_reverse_text', 1.0)),
    ({'reverse', 'words'}, ('tt_reverse_words', 1.0)),
    ({'random', 'word'}, ('fun_rand_word', 1.0)),
    ({'word', 'day', 'of'}, ('fun_word_day', 1.0)),
    ({'synonym'}, ('tt_synonym', 1.0)),
    ({'antonym'}, ('tt_antonym', 1.0)),
    ({'rhyme'}, ('tt_rhyme', 1.4)),
    ({'rhymes', 'with'}, ('tt_rhyme', 1.5)),
    ({'word', 'rhyme'}, ('tt_rhyme', 1.5)),
    ({'rhyme', 'words'}, ('tt_rhyme', 1.5)),
    ({'mode', 'focus'}, ('p_focus', 1.0)),
    ({'not', 'do', 'disturb'}, ('p_focus', 1.0)),
    ({'timer', 'work'}, ('p_focus', 0.9)),
    ({'break', 'timer'}, ('p_break', 0.9)),
    ({'habit', 'tracker'}, ('p_habit', 1.0)),
    ({'track', 'habit'}, ('p_habit', 1.0)),
    ({'habit'}, ('p_habit', 0.9)),
    ({'log', 'habit'}, ('p_habit', 1.0)),
    ({'streak'}, ('p_habit', 0.9)),
    ({'list', 'reading'}, ('p_reading_list', 1.0)),
    ({'read', 'add', 'to'}, ('p_reading_list', 0.9)),
    ({'list', 'book'}, ('p_reading_list', 0.9)),
    ({'shopping', 'list'}, ('p_shopping', 1.0)),
    ({'list', 'grocery'}, ('p_shopping', 1.0)),
    ({'shopping', 'add', 'to'}, ('p_shopping', 0.9)),
    ({'km', 'miles'}, ('me_unit_conv', 1.0)),
    ({'km', 'miles'}, ('me_unit_conv', 1.0)),
    ({'kg', 'pounds'}, ('me_unit_conv', 1.0)),
    ({'pounds', 'kg'}, ('me_unit_conv', 1.0)),
    ({'cm', 'inches'}, ('me_unit_conv', 1.0)),
    ({'cm', 'inches'}, ('me_unit_conv', 1.0)),
    ({'meters', 'feet'}, ('me_unit_conv', 1.0)),
    ({'meters', 'feet'}, ('me_unit_conv', 1.0)),
    ({'liters', 'gallons'}, ('me_unit_conv', 1.0)),
    ({'liters', 'gallons'}, ('me_unit_conv', 1.0)),
    ({'grams', 'ounces'}, ('me_unit_conv', 1.0)),
    ({'grams', 'ounces'}, ('me_unit_conv', 1.0)),
    ({'convert', 'unit'}, ('me_unit_conv', 1.0)),
    ({'convert', 'units'}, ('me_unit_conv', 1.0)),
    ({'http', 'status'}, ('dev_http_status', 1.0)),
    ({'status', 'code'}, ('dev_http_status', 0.9)),
    ({'color', 'hex'}, ('dev_color_hex', 1.0)),
    ({'hex', 'rgb', 'to'}, ('dev_color_hex', 1.0)),
    ({'hex', 'rgb', 'to'}, ('dev_color_hex', 1.0)),
    ({'color', 'picker'}, ('dev_color_hex', 0.9)),
    ({'char', 'code'}, ('dev_char_code', 1.0)),
    ({'ascii', 'code'}, ('dev_char_code', 1.0)),
    ({'unicode'}, ('dev_char_code', 0.9)),
    ({'help', 'cron'}, ('dev_cron', 1.0)),
    ({'format', 'cron'}, ('dev_cron', 1.0)),
    ({'cheat', 'regex'}, ('dev_regex_cheat', 1.0)),
    ({'help', 'regex'}, ('dev_regex_cheat', 0.9)),
    ({'help', 'markdown'}, ('dev_markdown', 1.0)),
    ({'markdown', 'syntax'}, ('dev_markdown', 0.9)),
    ({'help', 'git'}, ('dev_git_help', 1.0)),
    ({'cheat', 'git'}, ('dev_git_help', 0.9)),
    ({'help', 'sql'}, ('dev_sql_help', 1.0)),
    ({'cheat', 'sql'}, ('dev_sql_help', 0.9)),
    ({'help', 'docker'}, ('dev_docker_help', 1.0)),
    ({'periodic', 'table'}, ('sci_element', 1.0)),
    ({'element'}, ('sci_element', 0.8)),
    ({'atomic', 'number'}, ('sci_element', 1.0)),
    ({'symbol', 'chemical'}, ('sci_element', 1.0)),
    ({'constant', 'physics'}, ('sci_constant', 1.0)),
    ({'planck'}, ('sci_constant', 0.9)),
    ({'light', 'of', 'speed'}, ('sci_constant', 1.0)),
    ({'gravity'}, ('sci_constant', 0.9)),
    ({'avogadro'}, ('sci_constant', 1.0)),
    ({'ball', '8'}, ('fun_8ball', 1.0)),
    ({'ball', 'magic'}, ('fun_8ball', 1.0)),
    ({'you', 'rather', 'would'}, ('fun_wyr', 1.0)),
    ({'or', 'that', 'this'}, ('fun_wyr', 0.9)),
    ({'game', 'word'}, ('fun_word_game', 1.0)),
    ({'word', 'guess'}, ('fun_word_game', 0.9)),
    ({'trivia'}, ('fun_trivia', 1.0)),
    ({'quiz', 'me'}, ('fun_trivia', 0.9)),
    ({'teaser', 'brain'}, ('fun_teaser', 1.0)),
    ({'font', 'size'}, ('si2_font_size', 1.0)),
    ({'mode', 'dark'}, ('si_dark_mode', 1.0)),
    ({'mode', 'night'}, ('si_dark_mode', 0.9)),
    ({'wallpaper'}, ('si_wallpaper', 1.0)),
    ({'wallpaper', 'change'}, ('si_wallpaper', 1.0)),
    ({'what', 'day'}, ('p2_what_day', 1.0)),
    ({'week', 'day', 'of'}, ('p2_what_day', 1.0)),
    ({'days', 'between'}, ('p2_days_between', 1.0)),
    ({'date', 'difference'}, ('p2_days_between', 1.0)),
    ({'add', 'weeks'}, ('p2_date_add', 1.0)),
    ({'months', 'add'}, ('p2_date_add', 1.0)),
    ({'date', 'format'}, ('p2_date_fmt', 1.0)),
    ({'date', 'format'}, ('p2_date_fmt', 1.0)),
    ({'quarter'}, ('p2_quarter', 1.0)),
    ({'quarter', 'current'}, ('p2_quarter', 1.0)),
    ({'week', 'number'}, ('p2_week_num', 1.0)),
    ({'week', 'iso'}, ('p2_week_num', 0.9)),
    ({'mail', 'open'}, ('a2_mail', 1.0)),
    ({'maps', 'open'}, ('a2_maps', 1.0)),
    ({'google', 'maps'}, ('a2_maps', 1.0)),
    ({'photos', 'open'}, ('a2_photos', 1.0)),
    ({'music', 'open'}, ('a2_music', 1.0)),
    ({'whatsapp', 'open'}, ('a2_whatsapp', 1.0)),
    ({'telegram', 'open'}, ('a2_telegram', 1.0)),
    ({'slack', 'open'}, ('a2_slack', 1.0)),
    ({'zoom', 'open'}, ('a2_zoom', 1.0)),
    ({'teams', 'open'}, ('a2_teams', 1.0)),
    ({'obsidian', 'open'}, ('a2_obsidian', 1.0)),
    ({'notion', 'open'}, ('a2_notion', 1.0)),
    ({'jira', 'open'}, ('a2_jira', 1.0)),
    ({'postman', 'open'}, ('a2_postman', 1.0)),
    ({'dbeaver', 'open'}, ('a2_dbeaver', 1.0)),
    ({'android', 'studio', 'open'}, ('a2_android_studio', 1.0)),
    ({'go', 'to'}, ('mm_open_bookmark', 1.0)),
    ({'goto'}, ('mm_open_bookmark', 1.0)),
    ({'software', 'open'}, ('mm_open_software', 1.0)),
    ({'software', 'launch'}, ('mm_open_software', 1.0)),
    ({'list', 'bookmarks'}, ('mm_list_bookmarks', 1.0)),
    ({'show', 'bookmarks'}, ('mm_list_bookmarks', 1.0)),
    ({'bookmarks', 'my'}, ('mm_list_bookmarks', 1.0)),
    ({'add', 'bookmark'}, ('mm_add_bookmark', 1.0)),
    ({'save', 'bookmark'}, ('mm_add_bookmark', 1.0)),
    ({'list', 'software'}, ('mm_list_software', 1.0)),
    ({'software', 'show'}, ('mm_list_software', 1.0)),
    ({'apps', 'registered'}, ('mm_list_software', 1.0)),
    ({'selection', 'copy'}, ('mm_copy', 1.2)),
    ({'that', 'copy'}, ('mm_copy', 1.2)),
    ({'this', 'copy'}, ('mm_copy', 1.2)),
    ({'copy'}, ('mm_copy', 0.9)),
    ({'that', 'paste'}, ('mm_paste', 1.2)),
    ({'it', 'paste'}, ('mm_paste', 1.2)),
    ({'this', 'paste'}, ('mm_paste', 1.2)),
    ({'paste'}, ('mm_paste', 0.9)),
    ({'selection', 'cut'}, ('mm_cut', 1.2)),
    ({'that', 'cut'}, ('mm_cut', 1.2)),
    ({'this', 'cut'}, ('mm_cut', 1.2)),
    ({'cut'}, ('mm_cut', 0.9)),
    ({'all', 'select'}, ('mm_select_all', 1.3)),
    ({'everything', 'select'}, ('mm_select_all', 1.2)),
    ({'that', 'undo'}, ('mm_undo', 1.2)),
    ({'undo'}, ('mm_undo', 0.9)),
    ({'that', 'redo'}, ('mm_redo', 1.2)),
    ({'redo'}, ('mm_redo', 0.9)),
    ({'read', 'this'}, ('mm_read_selection', 1.3)),
    ({'selection', 'read'}, ('mm_read_selection', 1.3)),
    ({'aloud', 'read'}, ('mm_read_aloud', 1.3)),
    ({'read', 'that'}, ('mm_read_selection', 1.2)),
    ({'read', 'highlighted'}, ('mm_read_selection', 1.2)),
    ({'clipboard', 'read'}, ('mm_read_clipboard', 1.3)),
    ({'clipboard', 'what'}, ('mm_read_clipboard', 1.0)),
    ({'find', 'text'}, ('mm_find_text', 1.3)),
    ({'on', 'page', 'find'}, ('mm_find_text', 1.3)),
    ({'find', 'word'}, ('mm_find_text', 1.2)),
    ({'find', 'here'}, ('mm_find_text', 1.1)),
    ({'find'}, ('mm_find_text', 1.3)),
    ({'this', 'type'}, ('mm_type_text', 1.3)),
    ({'type', 'text'}, ('mm_type_text', 1.2)),
    ({'up', 'scroll'}, ('mm_scroll_up', 1.2)),
    ({'scroll', 'down'}, ('mm_scroll_dn', 1.2)),
    ({'scroll', 'top'}, ('mm_page_up', 1.1)),
    ({'bottom', 'scroll'}, ('mm_page_dn', 1.1)),
    ({'page', 'up'}, ('mm_page_up', 1.3)),
    ({'page', 'down'}, ('mm_page_dn', 1.3)),
    ({'tab', 'reopen'}, ('mm_reopen_tab', 1.4)),
    ({'page', 'reopen'}, ('mm_reopen_tab', 1.4)),
    ({'closed', 'reopen'}, ('mm_reopen_tab', 1.4)),
    ({'restore', 'tab'}, ('mm_reopen_tab', 1.3)),
    ({'next', 'tab'}, ('mm_tab_next', 1.2)),
    ({'tab', 'previous'}, ('mm_tab_prev', 1.2)),
    ({'next', 'tab'}, ('mm_tab_next', 1.2)),
    ({'tab', 'previous'}, ('mm_tab_prev', 1.2)),
    ({'prev', 'tab'}, ('mm_tab_prev', 1.2)),
    ({'tab', 'first'}, ('mm_tab_n', 1.4)),
    ({'second', 'tab'}, ('mm_tab_n', 1.4)),
    ({'third', 'tab'}, ('mm_tab_n', 1.4)),
    ({'tab', 'fourth'}, ('mm_tab_n', 1.4)),
    ({'tab', 'fifth'}, ('mm_tab_n', 1.4)),
    ({'sixth', 'tab'}, ('mm_tab_n', 1.4)),
    ({'seventh', 'tab'}, ('mm_tab_n', 1.4)),
    ({'tab', 'eighth'}, ('mm_tab_n', 1.4)),
    ({'ninth', 'tab'}, ('mm_tab_n', 1.4)),
    ({'page', 'first'}, ('mm_tab_n', 1.3)),
    ({'second', 'page'}, ('mm_tab_n', 1.3)),
    ({'third', 'page'}, ('mm_tab_n', 1.3)),
    ({'close', 'window'}, ('mm_close_window', 1.4)),
    ({'close', 'this', 'window'}, ('mm_close_window', 1.5)),
    ({'close', 'active', 'window'}, ('mm_close_window', 1.5)),
    ({'minimize'}, ('mm_minimize_app', 1.5)),
    ({'minimise'}, ('mm_minimize_app', 1.5)),
    ({'maximize'}, ('mm_maximize_app', 1.5)),
    ({'maximise'}, ('mm_maximize_app', 1.5)),
    ({'restore'}, ('mm_restore_app', 1.5)),
    ({'restore', 'window'}, ('mm_restore_app', 1.6)),
    ({'window', 'previous'}, ('mm_restore_app', 1.0)),
    ({'app', 'previous'}, ('mm_restore_app', 1.0)),
    ({'expand'}, ('mm_maximize_app', 1.4)),
    ({'shrink'}, ('mm_restore_app', 1.4)),
    ({'view', 'task'}, ('mm_task_view', 1.4)),
    ({'all', 'windows'}, ('mm_task_view', 1.3)),
    ({'view', 'all'}, ('mm_task_view', 1.3)),
    ({'all', 'show', 'windows'}, ('mm_task_view', 1.4)),
    ({'switch', 'window'}, ('mm_switch_window', 1.4)),
    ({'next', 'window'}, ('mm_switch_window', 1.3)),
    ({'show', 'desktop'}, ('mm_show_desktop', 1.5)),
    ({'center', 'notification'}, ('mm_notification_center', 1.5)),
    ({'center', 'action'}, ('mm_notification_center', 1.5)),
    ({'notifications'}, ('mm_notification_center', 1.2)),
    ({'magnifier'}, ('mm_magnifier', 1.4)),
    ({'magnify'}, ('mm_magnifier', 1.4)),
    ({'zoom', 'in'}, ('mm_magnifier', 1.2)),
    ({'snip'}, ('mm_snip', 1.4)),
    ({'snipping', 'tool'}, ('mm_snip', 1.5)),
    ({'screenshot', 'tool'}, ('mm_snip', 1.4)),
    ({'region', 'capture'}, ('mm_snip', 1.4)),
    ({'picker', 'emoji'}, ('mm_emoji', 1.4)),
    ({'research'}, ('mm_research', 1.0)),
    ({'here', 'incognito'}, ('mm_incognito_here', 1.5)),
    ({'here', 'private'}, ('mm_incognito_here', 1.5)),
    ({'search', 'incognito'}, ('mm_search_incognito', 1.5)),
    ({'search', 'private'}, ('mm_search_incognito', 1.5)),
    ({'search', 'incognito'}, ('mm_search_incognito', 1.4)),
    ({'arrow', 'up'}, ('mm_arrow_up', 1.4)),
    ({'arrow', 'down'}, ('mm_arrow_dn', 1.4)),
    ({'arrow', 'left'}, ('mm_arrow_left', 1.4)),
    ({'arrow', 'right'}, ('mm_arrow_right', 1.4)),
    ({'press', 'enter'}, ('mm_enter', 1.4)),
    ({'escape', 'press'}, ('mm_escape', 1.4)),
    ({'press', 'tab'}, ('mm_tab_key', 1.4)),
    ({'space', 'press'}, ('mm_space_key', 1.4)),
    ({'press', 'delete'}, ('mm_delete_key', 1.4)),
    ({'press', 'backspace'}, ('mm_backspace', 1.4)),
    ({'press', 'home'}, ('mm_home_key', 1.4)),
    ({'end', 'press'}, ('mm_end_key', 1.4)),
    ({'up'}, ('mm_arrow_up', 0.6)),
    ({'down'}, ('mm_arrow_dn', 0.6)),
    ({'left'}, ('mm_arrow_left', 0.6)),
    ({'right'}, ('mm_arrow_right', 0.6)),
    ({'enter'}, ('mm_enter', 0.7)),
    ({'escape'}, ('mm_escape', 0.8)),
    ({'spacebar'}, ('mm_space_key', 1.0)),
    ({'backspace'}, ('mm_backspace', 0.9)),
    ({'home'}, ('mm_home_key', 0.8)),
    ({'end'}, ('mm_end_key', 0.8)),
    # Antigravity Model Selection Triggers
    ({'cheapest', 'model'}, ('cfg_agy_model_cheapest', 1.5)),
    ({'use', 'cheapest', 'model'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'switch', 'cheapest', 'model'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'set', 'model', 'cheapest'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'use', 'flash', 'lite'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'switch', 'flash', 'lite'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'set', 'flash', 'lite'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'fastest', 'model'}, ('cfg_agy_model_cheapest', 1.5)),
    ({'use', 'fastest', 'model'}, ('cfg_agy_model_cheapest', 1.6)),
    ({'lightweight', 'model'}, ('cfg_agy_model_cheapest', 1.5)),
    ({'use', 'cheap', 'model'}, ('cfg_agy_model_cheapest', 1.5)),
    ({'cheapest', 'ai'}, ('cfg_agy_model_cheapest', 1.4)),

    ({'better', 'model'}, ('cfg_agy_model_better', 1.5)),
    ({'use', 'better', 'model'}, ('cfg_agy_model_better', 1.6)),
    ({'switch', 'better', 'model'}, ('cfg_agy_model_better', 1.6)),
    ({'set', 'model', 'better'}, ('cfg_agy_model_better', 1.6)),
    ({'use', 'flash', 'model'}, ('cfg_agy_model_better', 1.6)),
    ({'set', 'model', 'flash'}, ('cfg_agy_model_better', 1.6)),
    ({'balanced', 'model'}, ('cfg_agy_model_better', 1.5)),
    ({'use', 'balanced', 'model'}, ('cfg_agy_model_better', 1.6)),
    ({'standard', 'model'}, ('cfg_agy_model_better', 1.4)),
    ({'use', 'normal', 'model'}, ('cfg_agy_model_better', 1.4)),
    ({'better', 'ai'}, ('cfg_agy_model_better', 1.4)),

    ({'best', 'model'}, ('cfg_agy_model_best', 1.5)),
    ({'use', 'best', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'switch', 'best', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'set', 'model', 'best'}, ('cfg_agy_model_best', 1.6)),
    ({'use', 'pro', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'set', 'model', 'pro'}, ('cfg_agy_model_best', 1.6)),
    ({'smartest', 'model'}, ('cfg_agy_model_best', 1.5)),
    ({'use', 'smartest', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'highest', 'quality', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'deep', 'reasoning', 'model'}, ('cfg_agy_model_best', 1.6)),
    ({'best', 'ai'}, ('cfg_agy_model_best', 1.4)),

    ({'show', 'model'}, ('cfg_agy_model_show', 1.4)),
    ({'show', 'ai', 'model'}, ('cfg_agy_model_show', 1.5)),
    ({'current', 'model'}, ('cfg_agy_model_show', 1.4)),
    ({'current', 'ai', 'model'}, ('cfg_agy_model_show', 1.5)),
    ({'which', 'model'}, ('cfg_agy_model_show', 1.4)),
    ({'which', 'ai', 'model'}, ('cfg_agy_model_show', 1.5)),
    ({'what', 'ai', 'model'}, ('cfg_agy_model_show', 1.5)),
]
